# Backend image — FastAPI engine.
# Runs on port 8000 inside the docker network. Caddy reverse-proxies to it.

FROM python:3.11-slim AS base

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    PIP_NO_CACHE_DIR=1

# System deps for pyarrow (parquet) and openpyxl
RUN apt-get update \
 && apt-get install -y --no-install-recommends \
      build-essential libffi-dev \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy dependency manifests first so this layer caches across code changes.
#
# SUPPLY-CHAIN CONTRACT (locked 2026-08-23, after the 2026-08-22 boot-crash):
# every runtime dependency installs from requirements-lock.txt — the FULL
# hash-locked closure generated by scripts/generate_lock.py — under
# --require-hashes, so pip REFUSES anything unpinned, tampered, or newly
# floated (the old `pip install "anthropic>=0.30"` here is exactly how
# anthropic 1.0.0 entered a rebuild, dropped transitive httpx, and
# crash-looped the container). No pip invocation in this build may name a
# package outside the lock; scripts/check_supply_chain.py (C3) enforces it.
COPY pyproject.toml requirements-lock.txt ./
RUN pip install --require-hashes -r requirements-lock.txt

# Copy source + the canonical workbook + config
COPY src/ ./src/
COPY config.yaml ./
COPY files/ ./files/
# F4.2 — methodology YAML files (declarative EBITDA + ratio recipes).
# Required at runtime by engine.methodology.loader.load_methodology().
COPY methodology/ ./methodology/
# F3.16-3b.6-A (2026-05-26) — regression gates live alongside engine
# code. Pre-3b.6-A these were available in the running container only
# because of leftover docker-cp residue; the first clean rebuild
# wiped them and surfaced the gap. Adding here so future rebuilds
# carry the F4.2-PARITY / F-A3.1 / F-A3.2 / F-A3.3 gate scripts
# without manual docker-cp's. Sibling _pgrst_visibility helper +
# measure_bs_drift fixtures all live in scripts/.
COPY scripts/ ./scripts/
# Golden corpus — the in-container replay gate (scripts/corpus_replay.py)
# and the nightly prod canary need the cases + frozen goldens at /app/corpus.
COPY corpus/ ./corpus/
# Jurisdiction data packs — the RUNTIME classification source since the
# Phase 3 cutover (engine.packs.runtime resolves /app/packs from the
# module path; chart_of_accounts fails LOUDLY at import without it —
# there is no in-code rules fallback anymore).
COPY packs/ ./packs/
# F3.16-3b.2 — EEI JSON fixture source-of-truth lives in the FE tree
# (`scandi-desk-main/e2e/fixtures/...`) which is excluded by
# .dockerignore. To make the F-A3.2-CROSS-PATH gate run GREEN on EEI
# in-container, the fixture is also kept at `files/eei_expected_extraction.json`
# (already inside the build context). `files/` COPY above grabs it.
# Both copies must stay in sync — if the FE fixture changes,
# re-copy via: `cp scandi-desk-main/e2e/fixtures/.../expected_extraction.json files/eei_expected_extraction.json`

# Install the engine package itself so `python -m engine` resolves.
# --no-deps: the closure above IS the dependency set — pip must not
#   re-resolve anything outside the hash-checked lock.
# --no-build-isolation: the build backend (setuptools/wheel) is itself
#   pinned in the lock, so nothing is fetched for the build env either.
RUN pip install --no-deps --no-build-isolation -e .

# Persistent SQLite lives here (mounted as a named volume in compose)
RUN mkdir -p /app/data
VOLUME ["/app/data"]

EXPOSE 8000

# Single CMD — Caddy is the public-facing TLS terminator, so we bind to 0.0.0.0
# inside the docker network only.
CMD ["python", "-m", "engine", "serve", \
     "--config", "/app/config.yaml", \
     "--canonical-excel", "/app/files/Trading_analysis_YTDOct'25_LV.xlsx", \
     "--host", "0.0.0.0", \
     "--port", "8000", \
     "--db-url", "sqlite:////app/data/engine.db"]
