import { chromium } from "@playwright/test";
const OUT = "/Users/alex/Desktop/folder claude Scandia copy/design_review/markets/peer-add-r1";
const BASE = "http://localhost:5173";
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
await page.goto(`${BASE}/public-companies?market=us&lang=ro`, { waitUntil: "networkidle" });
await page.evaluate(() => localStorage.removeItem("cfo:benchmark-peers:v1"));
await page.reload({ waitUntil: "networkidle" });
await page.getByTestId("market-ticker-input-us").fill("AAPL");
await page.getByTestId("market-ticker-submit-us").click();
await page.getByTestId("market-peer-add-button-AAPL").waitFor();
await page.getByTestId("market-peer-add-button-AAPL").click();
await page.getByTestId("market-peer-added-AAPL").waitFor();
await page.getByTestId("market-peer-add-us-AAPL").scrollIntoViewIfNeeded();
await page.waitForTimeout(400);
await page.screenshot({ path: `${OUT}/08-ro-added-card.png` });
console.log(await page.getByTestId("market-peer-add-us-AAPL").innerText());
await page.evaluate(() => {
  const key = "cfo:benchmark-peers:v1";
  const cur = JSON.parse(localStorage.getItem(key) || "[]");
  cur.push({ticker:"TLV",name:"Banca Transilvania S.A.",sector:"Financials",exchange:"BVB",currency:"RON",marketId:"ro",source:"public",addedAt:new Date().toISOString()});
  cur.push({ticker:"SNP",name:"OMV Petrom S.A.",sector:"Energy",exchange:"BVB",currency:"RON",marketId:"ro",source:"public",addedAt:new Date().toISOString()});
  localStorage.setItem(key, JSON.stringify(cur));
});
await page.goto(`${BASE}/public-companies?tab=overview&lang=ro`, { waitUntil: "networkidle" });
await page.getByTestId("public-companies-benchmark-panel").scrollIntoViewIfNeeded();
await page.waitForTimeout(600);
await page.screenshot({ path: `${OUT}/09-ro-benchmark-cohorts.png` });
console.log(await page.getByTestId("public-companies-benchmark-panel").innerText());
await browser.close();
