// Landing-page copy, per language.
//
// The landing renders from static HTML template strings (see Landing.tsx), so
// it can't use react-i18next keys inline the way app surfaces do. Instead the
// templates are functions of one typed strings object, and the language
// picker in the landing header swaps which dictionary is passed in.
//
// Scope note: the three LEGAL DOCUMENTS (privacy / cookies / terms) are
// deliberately NOT translated — legal text needs a lawyer, not a model. They
// render in English with a translated notice (legal.englishNote).
//
// Tokens: FAQ answers may contain {privacy} / {terms}; the consent body may
// contain {cookiePolicy}. Landing.tsx replaces them with localized in-page
// link buttons.
//
// NO ACCURACY OR COVERAGE NUMBER IS TYPED IN THIS FILE (owner, 2026-10-01).
// The first public review found "eight calibration fixtures" in one sentence
// and "9 / 9" in the block beside it — both typed by hand, counting different
// things, neither dated. Every such number now arrives through a dotted
// token — {rerun.books}, {balance.exact}, {turnover.tol}, {bvb.listings},
// {coverage.ai_read.availability} … — filled from frontend/data/
// engineProof.json (generated by scripts/build_engine_proof.py, which RUNS
// the checks) and frontend/data/coverage.json. `LANDING_STRINGS` is the raw
// copy, tokens and all; `landingStringsFor()` returns it filled for a
// language. Gates `landing-proof` and `public-claims` red on a typed number
// and on a coverage claim that is not a row of coverage.json.

import type { FeatureKey } from "@/lib/features";
import { fillProofDeep, type ProofCheckId } from "@/lib/engineProof";

export interface LandingStrings {
  nav: { home: string; pricing: string; legal: string; contact: string; workspace: string; language: string };
  auth: { signIn: string; getStartedFree: string };
  menu: { openApp: string; settings: string; signOut: string };
  signout: { title: string; body: string; cancel: string; confirm: string };
  hero: {
    eyebrow: string;
    t1: string; thl: string; t2: string;
    body: string;
    ctaStart: string; ctaSignIn: string;
    checks: string[];
    mockNote: string;
    /** Title line of the fake browser chrome on the hero mock. */
    mockTitle: string;
    /** The illustrative dashboard under the hero, in the reader's language
     *  and number format. Invented figures, labelled illustrative by
     *  `mockNote`; none is a claim about the engine. */
    mock: {
      kpis: { label: string; value: string; unit: string; sub: string }[];
      briefingTitle: string;
      briefingBody: string;
      bullets: string[];
    };
  };
  stats: { drift: string; ratios: string; peers: string; upload: string };
  modules: {
    eyebrow: string; t1: string; thl: string;
    /** `featureKey` is the `_features.py` row the card sells. It is not
     *  decoration: `shippedClaimsMatchCode.test.ts` parses the real
     *  registry and reds when a card names a row that is not `active`.
     *  A fourth card ("Invoice Intelligence") was removed on 2026-09-08
     *  for exactly that reason — `invoices` is `hidden`, and its own
     *  PendingState says it waits on e-Factura ingestion nobody has
     *  built, while this card described it in the present tense as
     *  "surfaced as dedicated tabs inside your statements". */
    cards: { kicker: string; title: string; body: string; featureKey: FeatureKey }[];
  };
  how: {
    eyebrow: string; t1: string; thl: string;
    steps: { title: string; body: string }[];
  };
  /** The words around the coverage table beside the upload step. The table
   *  itself — every row, count and date — is frontend/data/coverage.json,
   *  rendered through lib/coverage. */
  coverage: { eyebrow: string; evidenceLabel: string; asOfLabel: string };
  /** The public sample: a FICTIONAL Romanian company's trial balance and
   *  the complete report generated from it (route /sample). */
  sample: { kicker: string; title: string; body: string; cta: string; proofCta: string };
  defensible: {
    eyebrow: string; title: string; body: string;
    bullets: { strong: string; rest: string }[];
    /** Engine proof block. The headline value of each row ("6 / 7"), what
     *  is checked and the date are read from engineProof.json; `captions`
     *  is the result in words, by check id, tokens only. `measured` carries
     *  `{when}`, which the page replaces with the row's own date. */
    proof: {
      label: string;
      captions: Record<ProofCheckId, string>;
      measured: string;
      note: string;
    };
  };
  audiences: {
    eyebrow: string; t1: string; thl: string;
    cards: { title: string; body: string }[];
  };
  faq: { eyebrow: string; title: string; items: { q: string; a: string }[] };
  cta: { t1: string; thl: string; body: string; start: string; signIn: string; goWorkspace: string };
  pricing: {
    eyebrow: string; t1: string; thl: string; subtitle: string; note: string; perMonth: string;
    solo: { name: string; yearly: string; blurb: string; cta: string; features: string[] };
    business: { badge: string; name: string; yearly: string; blurb: string; cta: string; lead: string[]; features: string[] };
    /** Multi-Country — COMING SOON. International coverage is not available
     *  (coverage.json row `other_countries`), so the card stays visible, is
     *  marked `badge`, and its `cta` is a disabled label, not a checkout link. */
    pro: { name: string; badge: string; price: string; priceNote: string; blurb: string; cta: string; lead: string[]; features: string[] };
  };
  legal: {
    eyebrow: string; title: string; subtitle: string; englishNote: string;
    privacy: string; cookies: string; terms: string;
  };
  contact: {
    eyebrow: string; title: string; subtitle: string;
    phName: string; phEmail: string; phCompany: string; phMessage: string;
    invalid: string; error: string; sending: string; send: string;
    sentTitle: string; sentBody: string; note: string;
    sales: { kicker: string; blurb: string };
    support: { kicker: string; blurb: string };
    privacy: { kicker: string; blurb: string };
    office: string;
  };
  footer: {
    blurb: string;
    product: string; overview: string; how: string; trust: string; audiences: string; faq: string;
    legalCol: string; cookieSettings: string;
    contactCol: string; contactUs: string;
    rights: string; madeIn: string;
  };
  consent: {
    title: string; body: string;
    necessary: string; necessaryDesc: string; alwaysOn: string;
    analytics: string; analyticsDesc: string;
    marketing: string; marketingDesc: string;
    acceptAll: string; rejectAll: string; save: string; customise: string;
  };
}

const en: LandingStrings = {
  nav: { home: "Home", pricing: "Pricing", legal: "Legal", contact: "Contact", workspace: "Workspace", language: "Language" },
  auth: { signIn: "Sign in", getStartedFree: "Get started" },
  menu: { openApp: "Open the app", settings: "Settings", signOut: "Sign out" },
  signout: {
    title: "Sign out of CFO AI?",
    body: "You'll be signed out on this device. Your workspaces, documents and analyses stay exactly where you left them.",
    cancel: "Cancel", confirm: "Sign out",
  },
  hero: {
    eyebrow: "CFO AI · Built for Romanian private businesses",
    t1: "Turn a Romanian trial balance into a ", thl: "CFO-grade analysis", t2: ".",
    body: "Upload your trial balance (balanță de verificare, RAS). CFO AI reconstructs your P&L and balance sheet, estimates your cash flow, and computes ratios, a valuation range and a credit score — then compares you with Romanian companies in your sector and turnover band, and with named companies listed on the Bucharest Stock Exchange.",
    ctaStart: "Get started", ctaSignIn: "Sign in",
    checks: ["7-day free trial", "Romanian trial balances (RAS)", "Cancel anytime"],
    mockNote: "Illustrative dashboard. In the product the briefing is written by an AI model.{coverage.briefing.status} AI-assisted analysis — final decisions remain with your management team.",
    mockTitle: "cfo-ai · today's briefing · 06:14",
    mock: {
      kpis: [
        { label: "EBITDA margin", value: "11.4", unit: "%", sub: "+1.8 pp vs sector" },
        { label: "Altman Z″", value: "3.12", unit: "", sub: "Safe zone" },
        { label: "Net debt / EBITDA", value: "1.8", unit: "×", sub: "Comfortable" },
        { label: "ROIC", value: "17.7", unit: "%", sub: "+2.1 pp vs last year" },
      ],
      briefingTitle: "AI CFO Briefing",
      briefingBody: "Profitability is above sector median, and the balance sheet is conservatively levered. Two watch-items: receivable days creeping up, and one supplier concentration above 30%.",
      bullets: ["DSO up 6 days — tighten collections", "Refinance short-term line before Q3", "Benchmark vs 3 named peers ready"],
    },
  },
  stats: { drift: "Balance-sheet drift", ratios: "Financial ratios", peers: "Public-company peers", upload: "Upload to report" },
  modules: {
    eyebrow: "Three flagship modules", t1: "One platform. ", thl: "Your books, or a company listed on the BVB.",
    cards: [
      { kicker: "Trial balance → board-ready report", title: "Financial Statement Intelligence", body: "A Romanian trial balance (RAS), exported from your accounting software as Excel or PDF. Accounts are mapped to the statements by the engine, then turned into ratios, a credit score and ranked recommendations. The coverage table below lists exactly which file layouts are tested, and on how many real books.", featureKey: "upload_trial_balance" },
      { kicker: "BVB tickers → company pages", title: "Public Company Intelligence", body: "{bvb.listings} listings on the Bucharest Stock Exchange, with delayed quotes. {bvb.withFinancials} of them carry summary financial figures today — annual-report figures for the main index, the latest statutory filing for others. Add any of them as a benchmark peer.", featureKey: "public_companies" },
      { kicker: "Ask questions → grounded answers", title: "Ask CFO AI", body: "A financial copilot that answers from your own statements. Ask why margin moved, what a ratio means, or what to do next — it names the period and the figure it used. Its answers are written by an AI model.{coverage.chat.status}", featureKey: "chat_page" },
    ],
  },
  how: {
    eyebrow: "How it works", t1: "Three steps from spreadsheet to ", thl: "action plan.",
    steps: [
      { title: "Upload your trial balance", body: "A Romanian trial balance (balanță de verificare), exported from your accounting software as Excel or PDF. Columns and RAS accounts are mapped by the engine. The table below says exactly what is tested." },
      { title: "CFO AI computes the economics", body: "P&amp;L, balance sheet, a cash-flow estimate, ratios, EBITDA variants, Altman Z, a valuation range and a credit score. {checks.upload}" },
      { title: "You act with context", body: "Ranked, quantified recommendations plus named public-company peers — export to HTML or a 9-sheet Excel model." },
    ],
  },
  coverage: { eyebrow: "Coverage", evidenceLabel: "Evidence", asOfLabel: "as of" },
  sample: {
    kicker: "Public sample",
    title: "Inspect a sample report before you upload anything.",
    body: "A fictional Romanian company — its trial balance, the report the product exports from it, every account-to-line mapping and every uncertainty label. The sample has no valuation, no sector benchmarks and no AI briefing. Fictional data, the real engine — and the issues we know this report has are listed at its top.",
    cta: "Open the sample report",
    proofCta: "See these checks on the sample report",
  },
  defensible: {
    eyebrow: "Checked, and dated",
    title: "Numbers you can check, not numbers you have to trust.",
    body: "For a Romanian trial balance in one of the tested layouts in the coverage table, the engine is deterministic: the numbers are read and computed by code, never by an AI model. A scan, or a layout the readers do not recognise, needs the AI reader, and its result is labelled as AI-read. We publish what we check, on how many real books, and on what date — the block alongside is written by the test run itself, not typed. When a source file has an imbalance, CFO AI shows it rather than smoothing it over.",
    bullets: [
      { strong: "Reproducible.", rest: "The same trial balance gives the same output — re-run and compared byte for byte." },
      { strong: "Traceable.", rest: "Every account is mapped to a named statement line, and the mapping is part of the result — the public sample lists all of it." },
      { strong: "Honest about uncertainty.", rest: "Approximations are labelled; where a figure cannot be computed, the report says so instead of printing a zero." },
    ],
    proof: {
      label: "Engine proof · measured checks",
      captions: {
        rerun_identical: "{rerun.books} of {rerun.subjects} real books, re-run {rerun.runs} times each: the statement envelope is byte-identical every time. {replay.identical} of {replay.cases} replay cases ({replay.real} real books, {replay.constructed} constructed test files) reproduce their stored results.",
        balance_sheet_closes: "{balance.exact} of {balance.subjects} real books close to exactly {balance.zero} as served. On the remaining {balance.surfaced}, the source file itself does not balance and the report shows the difference. An older internal drift measure reads at most {drift.worst} across {drift.books} books.",
        net_income_equals_121: "{net.equal} of {net.subjects} real books: the net income served equals account 121 to the cent.",
        turnover_equals_filing: "{turnover.within} of {turnover.subjects} books whose trial balance is the filed year match the Ministry-of-Finance figure within {turnover.tol}. The other {turnover.unchecked} of our {proof.books} real books are preliminary closes or have no filing on hand, and are not claimed.",
        ebitda_variants_agree: "{ebitda.within} of {ebitda.subjects} real books: the methodology and the code agree on all {ebitda.variants} variants within {ebitda.tol}.",
      },
      measured: "measured {when}",
      note: "Written by scripts/build_engine_proof.py from a test run on real Romanian trial balances. Each book is counted once; no company is named. These are checks on our test books. {checks.upload} The other checks here are run on the test books only.",
    },
  },
  audiences: {
    eyebrow: "Who it's for", t1: "Built for whoever reads the ", thl: "numbers.",
    cards: [
      { title: "Founders &amp; owners", body: "Understand your own financials the way an analyst would — and see exactly where you stand against real peers." },
      { title: "Finance teams", body: "Turn a month-end trial balance into board-ready statements, ratios and a credit score without rebuilding a model." },
      { title: "Investors &amp; analysts", body: "Run due diligence on a private Romanian target from its trial balance, and set it beside companies listed on the BVB." },
      { title: "Advisors &amp; accountants", body: "Deliver CFO-grade analyses across a portfolio of client companies — the same framework for each one." },
      { title: "Lenders", body: "Screen credit with Altman Z″, coverage ratios and covenant-ready strict EBITDA — with the source reconciliation shown." },
      { title: "Family offices", body: "Review multiple group entities and holdings on one consistent framework, including NAV for asset-heavy vehicles." },
    ],
  },
  faq: {
    eyebrow: "Questions", title: "Frequently asked",
    items: [
      { q: "What file formats can I upload?", a: "A Romanian trial balance (balanță de verificare) as an Excel .xlsx sheet or as a PDF with a text layer, in one of the layouts the coverage table on this page lists — with how many real books each was tested on, how many real files were refused, and what is not supported yet. Scanned PDFs, photos, a trial balance in a layout the readers do not recognise, and statements that are not a trial balance (a balance sheet, a P&amp;L, an annual report) need the AI reader — its status is in the same table." },
      { q: "What do you check, and on how many books?", a: "We do not publish an accuracy percentage. We publish what was checked, on how many real Romanian trial balances, and when (measured {proof.date}). Re-runs are byte-identical on {rerun.books} of {rerun.subjects} books. The balance sheet as served closes exactly on {balance.exact} of {balance.subjects}; on the remaining {balance.surfaced} the source itself does not balance and the report shows the difference. Net income equals account 121 on {net.equal} of {net.subjects}. Turnover matches the Ministry-of-Finance filing within {turnover.tol} on {turnover.within} of {turnover.subjects} books whose trial balance is the filed year; the other {turnover.unchecked} are preliminary closes or have no filing on hand, and are not claimed. The three EBITDA variants agree between the methodology and the code within {ebitda.tol} on {ebitda.within} of {ebitda.subjects}. {checks.upload} The other checks are run on our test books only. It is a decision-support tool, not a substitute for professional judgement." },
      { q: "Is my financial data secure?", a: "Your data is stored on EU-region infrastructure with row-level security so only your account can access it. We never sell your data. Where a document or a question is processed by the AI model, that content is sent to our model provider in the United States. See our {privacy} for the full detail on sub-processors and your rights under the GDPR." },
      { q: "Do you offer a free trial?", a: "Yes — a free trial: one document, for 7 days, with no card required. A paid plan is charged from the day you subscribe, and you can cancel it at any time." },
      { q: "Which countries and accounting standards are supported?", a: "Romania only, today: trial balances kept under Romanian accounting standards (RAS, OMFP 1802). Files from other countries are not supported yet, and the Multi-Country plan is not available. Public-company pages cover {bvb.listings} listings on the Bucharest Stock Exchange; {bvb.withFinancials} of them carry financial figures today." },
      { q: "Is this financial or investment advice?", a: "No. CFO AI produces AI-assisted analysis and decision support. It is not financial, investment, legal, tax or accounting advice, and final decisions remain with you and your management team. See our {terms}." },
    ],
  },
  cta: {
    t1: "See your business the way a ", thl: "CFO would.",
    body: "Upload your first Romanian trial balance and get the full analysis. No credit card required for the 7-day trial.",
    start: "Get started", signIn: "Sign in", goWorkspace: "Go to workspace",
  },
  pricing: {
    eyebrow: "Pricing", t1: "Simple plans that ", thl: "scale with you.",
    subtitle: "Start free with one document. Upgrade when you need more. Cancel anytime.",
    note: "All prices exclude VAT where applicable. Extra documents are billed per document and always confirmed before processing.",
    perMonth: "/mo",
    solo: {
      name: "RO Solo", yearly: "3 trial balances / month · 1 company workspace",
      blurb: "One Romanian company, the full CFO-grade analysis, every month.",
      cta: "Start with RO Solo",
      features: ["1 company workspace", "3 trial balances / month ({price.solo_extra} per extra)", "8-section analysis page &amp; exported report", "P&amp;L, balance sheet, cash-flow estimate, ratios, valuation range &amp; credit score", "Ask CFO AI: 10 chats / day, 50 / month{coverage.chat.suffix}", "Exports &amp; email support"],
    },
    business: {
      badge: "Most popular", name: "Pro", yearly: "15 trial balances / month · up to 5 company workspaces",
      blurb: "Groups of SRLs, internal finance teams and advisors running several companies.",
      cta: "Start with Pro",
      lead: ["Up to 5 company workspaces", "The same analysis as RO Solo, with higher limits:"],
      features: ["15 trial balances / month ({price.pro_extra} per extra)", "Ask CFO AI: 25 chats / day, 150 / month{coverage.chat.suffix}"],
    },
    pro: {
      name: "Multi-Country", badge: "Coming soon", price: "{price.multi}", priceNote: "/mo — not on sale yet",
      blurb: "Coming soon — international coverage is not available yet. Today CFO AI reads Romanian trial balances only.",
      cta: "Coming soon",
      lead: ["Everything in Pro", "Planned, not available yet:"],
      features: ["Trial balances from countries other than Romania", "200 Ask CFO AI chats / month", "Up to 5 company workspaces"],
    },
  },
  legal: {
    eyebrow: "Legal", title: "The fine print, in plain sight.",
    subtitle: "How CFO AI handles your data, and the terms that govern the service — all on one page.",
    englishNote: "",
    privacy: "Privacy Policy", cookies: "Cookie Policy", terms: "Terms of Service",
  },
  contact: {
    eyebrow: "Contact", title: "Talk to us.",
    subtitle: "Whether you're evaluating CFO AI for a portfolio of companies or just have a question — we'd like to hear from you.",
    phName: "Your name *", phEmail: "Email *", phCompany: "Company (optional)", phMessage: "How can we help? *",
    invalid: "Please fill in your name, a valid email and a message.",
    error: `Couldn't send your message. Please try again, or email <a href="mailto:support@cfo-ai.io">support@cfo-ai.io</a> directly.`,
    sending: "Sending…", send: "Send",
    sentTitle: "Message sent.", sentBody: "Thanks for reaching out — we'll get back to you within one business day.",
    note: "By sending, you agree we may email you back about your request. See our Privacy Policy.",
    sales: { kicker: "Sales", blurb: "Plans, limits and anything you need answered before you buy." },
    support: { kicker: "Support", blurb: "Help with your account, uploads or analyses." },
    privacy: { kicker: "Privacy &amp; data", blurb: "Exercise your GDPR rights or ask about data." },
    office: "Registered office",
  },
  footer: {
    blurb: "CFO-grade financial analysis and benchmarking for Romanian private businesses.",
    product: "Product", overview: "Overview", how: "How it works", trust: "Why trust it", audiences: "Who it's for", faq: "FAQ",
    legalCol: "Legal", cookieSettings: "Cookie settings",
    contactCol: "Contact", contactUs: "Contact us",
    rights: "© {year} CFO AI · {company}. All rights reserved.",
    madeIn: "Made in the EU · GDPR-compliant",
  },
  consent: {
    title: "We value your privacy",
    body: "We use strictly necessary cookies to run CFO AI, and — only with your consent — optional analytics and marketing cookies. You can accept all, reject optional ones, or choose. Read our {cookiePolicy}.",
    necessary: "Strictly necessary", necessaryDesc: "Required for sign-in, security and saving your choice.", alwaysOn: "Always on",
    analytics: "Analytics", analyticsDesc: "Helps us improve the product.",
    marketing: "Marketing", marketingDesc: "Measures campaigns and relevance.",
    acceptAll: "Accept all", rejectAll: "Reject optional", save: "Save choices", customise: "Customise",
  },
};

const ro: LandingStrings = {
  nav: { home: "Acasă", pricing: "Prețuri", legal: "Legal", contact: "Contact", workspace: "Spațiu de lucru", language: "Limbă" },
  auth: { signIn: "Autentificare", getStartedFree: "Începe" },
  menu: { openApp: "Deschide aplicația", settings: "Setări", signOut: "Deconectare" },
  signout: {
    title: "Te deconectezi de la CFO AI?",
    body: "Vei fi deconectat pe acest dispozitiv. Spațiile de lucru, documentele și analizele tale rămân exact unde le-ai lăsat.",
    cancel: "Anulează", confirm: "Deconectare",
  },
  hero: {
    eyebrow: "CFO AI · Creat pentru afaceri private din România",
    t1: "Transformă o balanță de verificare românească într-o ", thl: "analiză de nivel CFO", t2: ".",
    body: "Încarcă-ți balanța de verificare (RAS). CFO AI reconstruiește contul de profit și pierdere și bilanțul, estimează fluxul de numerar și calculează indicatori, un interval de evaluare și un scor de credit — apoi te compară cu firmele românești din sectorul și din banda ta de cifră de afaceri și cu companii listate la Bursa de Valori București, numite explicit.",
    ctaStart: "Începe", ctaSignIn: "Autentificare",
    checks: ["Probă gratuită de 7 zile", "Balanțe de verificare românești (RAS)", "Anulezi oricând"],
    mockNote: "Dashboard ilustrativ. În produs, briefingul este scris de un model AI.{coverage.briefing.status} Analiză asistată de AI — deciziile finale rămân la echipa ta de management.",
    mockTitle: "cfo-ai · briefingul de azi · 06:14",
    mock: {
      kpis: [
        { label: "Marja EBITDA", value: "11,4", unit: "%", sub: "+1,8 pp față de sector" },
        { label: "Altman Z″", value: "3,12", unit: "", sub: "Zonă sigură" },
        { label: "Datorie netă / EBITDA", value: "1,8", unit: "×", sub: "Confortabil" },
        { label: "ROIC", value: "17,7", unit: "%", sub: "+2,1 pp față de anul trecut" },
      ],
      briefingTitle: "Briefing AI CFO",
      briefingBody: "Profitabilitatea este peste mediana sectorului, iar bilanțul este îndatorat prudent. Două puncte de urmărit: zilele de încasare cresc, iar un furnizor depășește 30% din achiziții.",
      bullets: ["DSO a crescut cu 6 zile — strânge încasările", "Refinanțează linia pe termen scurt înainte de T3", "Comparația cu 3 companii numite este gata"],
    },
  },
  stats: { drift: "Abatere de bilanț", ratios: "Indicatori financiari", peers: "Companii publice comparabile", upload: "De la încărcare la raport" },
  modules: {
    eyebrow: "Trei module emblematice", t1: "O singură platformă. ", thl: "Contabilitatea ta sau o companie listată la BVB.",
    cards: [
      { kicker: "Balanță de verificare → raport pentru board", title: "Financial Statement Intelligence", body: "O balanță de verificare românească (RAS), exportată din programul tău de contabilitate în Excel sau PDF. Conturile sunt mapate pe situații de către motor, apoi transformate în indicatori, un scor de credit și recomandări ierarhizate. Tabelul de acoperire de mai jos arată exact ce formate de fișier sunt testate și pe câte balanțe reale.", featureKey: "upload_trial_balance" },
      { kicker: "Tickere BVB → pagini de companie", title: "Public Company Intelligence", body: "{bvb.listings} de listări la Bursa de Valori București, cu cotații cu întârziere. {bvb.withFinancials} dintre ele au astăzi cifre financiare sumare — cifre din rapoartele anuale pentru indicele principal, ultima raportare statutară pentru celelalte. Adaugă oricare drept reper de comparație.", featureKey: "public_companies" },
      { kicker: "Pui întrebări → răspunsuri fundamentate", title: "Ask CFO AI", body: "Un copilot financiar care răspunde din propriile tale situații. Întreabă de ce s-a mișcat marja, ce înseamnă un indicator sau ce urmează — numește perioada și cifra pe care le-a folosit. Răspunsurile sunt scrise de un model AI.{coverage.chat.status}", featureKey: "chat_page" },
    ],
  },
  how: {
    eyebrow: "Cum funcționează", t1: "Trei pași de la foaia de calcul la ", thl: "planul de acțiune.",
    steps: [
      { title: "Încarcă-ți balanța de verificare", body: "O balanță de verificare românească, exportată din programul tău de contabilitate în Excel sau PDF. Coloanele și conturile RAS sunt mapate de motor. Tabelul de mai jos spune exact ce este testat." },
      { title: "CFO AI calculează economia afacerii", body: "Cont de profit și pierdere, bilanț, o estimare a fluxului de numerar, indicatori, variante de EBITDA, Altman Z, un interval de evaluare și un scor de credit. {checks.upload}" },
      { title: "Tu acționezi în cunoștință de cauză", body: "Recomandări ierarhizate și cuantificate plus companii publice comparabile, numite explicit — export în HTML sau model Excel cu 9 foi." },
    ],
  },
  coverage: { eyebrow: "Acoperire", evidenceLabel: "Dovadă", asOfLabel: "la data de" },
  sample: {
    kicker: "Exemplu public",
    title: "Examinează un raport-exemplu înainte să încarci ceva.",
    body: "O companie românească fictivă — balanța ei de verificare, raportul pe care produsul îl exportă din ea, fiecare mapare cont → linie și fiecare etichetă de incertitudine. Exemplul nu are evaluare, comparații cu sectorul sau rezumat scris de AI. Date fictive, motorul real — iar problemele pe care știm că le are acest raport sunt listate la începutul lui.",
    cta: "Deschide raportul-exemplu",
    proofCta: "Vezi aceste verificări pe raportul-exemplu",
  },
  defensible: {
    eyebrow: "Verificat și datat",
    title: "Cifre pe care le poți verifica, nu cifre pe care trebuie să le crezi.",
    body: "Pentru o balanță de verificare românească într-unul dintre formatele testate din tabelul de acoperire, motorul este determinist: cifrele sunt citite și calculate de cod, niciodată de un model AI. Un document scanat sau un format pe care cititoarele nu îl recunosc are nevoie de cititorul AI, iar rezultatul este etichetat „Citit de AI”. Publicăm ce verificăm, pe câte balanțe reale și la ce dată — blocul alăturat este scris chiar de rularea testelor, nu tastat. Când un fișier-sursă are un dezechilibru, CFO AI îl arată în loc să-l netezească.",
    bullets: [
      { strong: "Reproductibil.", rest: "Aceeași balanță de verificare dă același rezultat — rulat din nou și comparat octet cu octet." },
      { strong: "Trasabil.", rest: "Fiecare cont este mapat pe o linie numită din situații, iar maparea face parte din rezultat — exemplul public o listează în întregime." },
      { strong: "Onest cu incertitudinea.", rest: "Aproximările sunt etichetate; acolo unde o cifră nu poate fi calculată, raportul spune asta în loc să afișeze un zero." },
    ],
    proof: {
      label: "Proba motorului · verificări măsurate",
      captions: {
        rerun_identical: "{rerun.books} din {rerun.subjects} balanțe reale, rulate de {rerun.runs} ori fiecare: pachetul de situații este identic octet cu octet de fiecare dată. {replay.identical} din {replay.cases} cazuri de reluare ({replay.real} balanțe reale, {replay.constructed} fișiere de test construite) își reproduc rezultatele stocate.",
        balance_sheet_closes: "{balance.exact} din {balance.subjects} balanțe reale se închid exact la {balance.zero}, așa cum sunt afișate. La restul de {balance.surfaced}, fișierul-sursă nu se echilibrează, iar raportul afișează diferența. O măsură internă mai veche a abaterii indică cel mult {drift.worst} pe {drift.books} balanțe.",
        net_income_equals_121: "{net.equal} din {net.subjects} balanțe reale: rezultatul net afișat este egal cu contul 121, la ban.",
        turnover_equals_filing: "{turnover.within} din {turnover.subjects} balanțe care sunt închiderea de an depusă corespund cifrei de la Ministerul Finanțelor, în limita a {turnover.tol}. Celelalte {turnover.unchecked} din cele {proof.books} balanțe reale ale noastre sunt închideri preliminare sau nu au o raportare la îndemână și nu sunt revendicate.",
        ebitda_variants_agree: "{ebitda.within} din {ebitda.subjects} balanțe reale: metodologia și codul dau aceeași valoare pentru toate cele {ebitda.variants} variante, în limita a {ebitda.tol}.",
      },
      measured: "măsurat la {when}",
      note: "Scris de scripts/build_engine_proof.py dintr-o rulare de teste pe balanțe de verificare românești reale. Fiecare balanță este numărată o singură dată; nicio companie nu este numită. Acestea sunt verificări pe balanțele noastre de test. {checks.upload} Celelalte verificări de aici se rulează doar pe balanțele de test.",
    },
  },
  audiences: {
    eyebrow: "Pentru cine este", t1: "Creat pentru oricine citește ", thl: "cifrele.",
    cards: [
      { title: "Fondatori &amp; proprietari", body: "Înțelege-ți propriile finanțe așa cum ar face-o un analist — și vezi exact unde te situezi față de companii comparabile reale." },
      { title: "Echipe financiare", body: "Transformă balanța de la închiderea lunii în situații pentru board, indicatori și un scor de credit, fără a reconstrui un model." },
      { title: "Investitori &amp; analiști", body: "Rulează due diligence pe o țintă privată românească pornind de la balanța ei de verificare și pune-o lângă companii listate la BVB." },
      { title: "Consultanți &amp; contabili", body: "Livrează analize de nivel CFO pentru un portofoliu de clienți — același cadru pentru fiecare." },
      { title: "Creditori", body: "Evaluează riscul de credit cu Altman Z″, indicatori de acoperire și EBITDA strict pregătit pentru covenante — cu reconcilierea sursei afișată." },
      { title: "Family office-uri", body: "Analizează mai multe entități de grup și participații într-un cadru unic și consecvent, inclusiv NAV pentru vehicule cu active semnificative." },
    ],
  },
  faq: {
    eyebrow: "Întrebări", title: "Întrebări frecvente",
    items: [
      { q: "Ce formate de fișiere pot încărca?", a: "O balanță de verificare românească în Excel (.xlsx) sau în PDF cu strat de text, într-unul dintre formatele din tabelul de acoperire de pe această pagină — care arată și pe câte balanțe reale a fost testat fiecare, câte fișiere reale au fost refuzate și ce nu este încă suportat. PDF-urile scanate, fotografiile, o balanță într-un format pe care cititoarele nu îl recunosc și situațiile care nu sunt o balanță de verificare (un bilanț, un cont de profit și pierdere, un raport anual) au nevoie de cititorul AI — starea lui este în același tabel." },
      { q: "Ce verificați și pe câte balanțe?", a: "Nu publicăm un procent de acuratețe. Publicăm ce a fost verificat, pe câte balanțe de verificare românești reale și când (măsurat la {proof.date}). Rerulările sunt identice octet cu octet pe {rerun.books} din {rerun.subjects} balanțe. Bilanțul, așa cum este afișat, se închide exact pe {balance.exact} din {balance.subjects}; la restul de {balance.surfaced}, sursa nu se echilibrează, iar raportul afișează diferența. Rezultatul net este egal cu contul 121 pe {net.equal} din {net.subjects}. Cifra de afaceri corespunde raportării depuse la Ministerul Finanțelor, în limita a {turnover.tol}, pe {turnover.within} din {turnover.subjects} balanțe care sunt închiderea de an depusă; celelalte {turnover.unchecked} sunt închideri preliminare sau nu au o raportare la îndemână și nu sunt revendicate. Cele trei variante de EBITDA coincid între metodologie și cod, în limita a {ebitda.tol}, pe {ebitda.within} din {ebitda.subjects}. {checks.upload} Celelalte verificări se rulează doar pe balanțele noastre de test. Este un instrument de suport decizional, nu un substitut pentru judecata profesională." },
      { q: "Datele mele financiare sunt în siguranță?", a: "Datele tale sunt stocate pe infrastructură din regiunea UE, cu securitate la nivel de rând, astfel încât doar contul tău le poate accesa. Nu îți vindem niciodată datele. Atunci când un document sau o întrebare este procesată de modelul AI, acel conținut este trimis furnizorului nostru de model din Statele Unite. Vezi {privacy} pentru detalii complete despre subprocesatori și drepturile tale conform GDPR." },
      { q: "Oferiți o perioadă de probă gratuită?", a: "Da — o probă gratuită: un document, timp de 7 zile, fără card. Un plan plătit se taxează din ziua în care te abonezi și îl poți anula oricând." },
      { q: "Ce țări și standarde contabile sunt suportate?", a: "Doar România, astăzi: balanțe de verificare ținute după reglementările contabile românești (RAS, OMFP 1802). Fișierele din alte țări nu sunt încă suportate, iar planul Multi-Country nu este disponibil. Paginile de companii publice acoperă {bvb.listings} de listări la Bursa de Valori București; {bvb.withFinancials} dintre ele au astăzi cifre financiare." },
      { q: "Aceasta este consultanță financiară sau de investiții?", a: "Nu. CFO AI produce analiză asistată de AI și suport decizional. Nu reprezintă consultanță financiară, de investiții, juridică, fiscală sau contabilă, iar deciziile finale rămân la tine și la echipa ta de management. Vezi {terms}." },
    ],
  },
  cta: {
    t1: "Vezi-ți afacerea așa cum ar vedea-o un ", thl: "CFO.",
    body: "Încarcă prima ta balanță de verificare românească și primești analiza completă. Fără card pentru proba de 7 zile.",
    start: "Începe gratuit", signIn: "Autentificare", goWorkspace: "Mergi la spațiul de lucru",
  },
  pricing: {
    eyebrow: "Prețuri", t1: "Planuri simple care ", thl: "cresc odată cu tine.",
    subtitle: "Începe gratuit cu un document. Faci upgrade când ai nevoie de mai mult. Anulezi oricând.",
    note: "Toate prețurile nu includ TVA, acolo unde este cazul. Documentele suplimentare se facturează per document și sunt întotdeauna confirmate înainte de procesare.",
    perMonth: "/lună",
    solo: {
      name: "RO Solo", yearly: "3 balanțe de verificare / lună · 1 spațiu de lucru",
      blurb: "O companie românească, analiza completă de nivel CFO, în fiecare lună.",
      cta: "Începe cu RO Solo",
      features: ["1 spațiu de lucru", "3 balanțe de verificare / lună ({price.solo_extra} per balanță suplimentară)", "Pagină de analiză în 8 secțiuni &amp; raport exportat", "Cont de profit și pierdere, bilanț, estimare a fluxului de numerar, indicatori, interval de evaluare &amp; scor de credit", "Ask CFO AI: 10 conversații / zi, 50 / lună{coverage.chat.suffix}", "Exporturi &amp; suport pe e-mail"],
    },
    business: {
      badge: "Cel mai popular", name: "Pro", yearly: "15 balanțe de verificare / lună · până la 5 spații de lucru",
      blurb: "Grupuri de SRL-uri, echipe financiare interne și consultanți care administrează mai multe companii.",
      cta: "Începe cu Pro",
      lead: ["Până la 5 spații de lucru", "Aceeași analiză ca în RO Solo, cu limite mai mari:"],
      features: ["15 balanțe de verificare / lună ({price.pro_extra} per balanță suplimentară)", "Ask CFO AI: 25 de conversații / zi, 150 / lună{coverage.chat.suffix}"],
    },
    pro: {
      name: "Multi-Country", badge: "În curând", price: "{price.multi}", priceNote: "/lună — încă nu este de vânzare",
      blurb: "În curând — acoperirea internațională nu este încă disponibilă. Astăzi CFO AI citește doar balanțe de verificare românești.",
      cta: "În curând",
      lead: ["Tot ce e în Pro", "Planificat, încă indisponibil:"],
      features: ["Balanțe de verificare din alte țări decât România", "200 de conversații Ask CFO AI / lună", "Până la 5 spații de lucru"],
    },
  },
  legal: {
    eyebrow: "Legal", title: "Termenii, la vedere.",
    subtitle: "Cum gestionează CFO AI datele tale și termenii care guvernează serviciul — totul pe o singură pagină.",
    englishNote: "Documentele juridice de mai jos sunt furnizate în limba engleză.",
    privacy: "Politica de confidențialitate", cookies: "Politica de cookie-uri", terms: "Termenii serviciului",
  },
  contact: {
    eyebrow: "Contact", title: "Hai să vorbim.",
    subtitle: "Fie că evaluezi CFO AI pentru un portofoliu de companii, fie că ai doar o întrebare — ne-ar plăcea să te auzim.",
    phName: "Numele tău *", phEmail: "E-mail *", phCompany: "Compania (opțional)", phMessage: "Cu ce te putem ajuta? *",
    invalid: "Te rugăm să completezi numele, un e-mail valid și un mesaj.",
    error: `Mesajul nu a putut fi trimis. Încearcă din nou sau scrie-ne direct la <a href="mailto:support@cfo-ai.io">support@cfo-ai.io</a>.`,
    sending: "Se trimite…", send: "Trimite",
    sentTitle: "Mesaj trimis.", sentBody: "Mulțumim că ne-ai scris — revenim în cel mult o zi lucrătoare.",
    note: "Prin trimitere, ești de acord să te contactăm pe e-mail în legătură cu solicitarea ta. Vezi Politica de confidențialitate.",
    sales: { kicker: "Vânzări", blurb: "Planuri, limite și orice altceva vrei lămurit înainte să cumperi." },
    support: { kicker: "Suport", blurb: "Ajutor cu contul, încărcările sau analizele tale." },
    privacy: { kicker: "Confidențialitate &amp; date", blurb: "Exercită-ți drepturile GDPR sau întreabă despre date." },
    office: "Sediu social",
  },
  footer: {
    blurb: "Analiză financiară de nivel CFO și benchmarking pentru afaceri private din România.",
    product: "Produs", overview: "Prezentare", how: "Cum funcționează", trust: "De ce e de încredere", audiences: "Pentru cine este", faq: "Întrebări frecvente",
    legalCol: "Legal", cookieSettings: "Setări cookie-uri",
    contactCol: "Contact", contactUs: "Contactează-ne",
    rights: "© {year} CFO AI · {company}. Toate drepturile rezervate.",
    madeIn: "Creat în UE · Conform GDPR",
  },
  consent: {
    title: "Îți respectăm confidențialitatea",
    body: "Folosim cookie-uri strict necesare pentru funcționarea CFO AI și — doar cu acordul tău — cookie-uri opționale de analiză și marketing. Poți accepta tot, respinge opționalele sau alege. Citește {cookiePolicy}.",
    necessary: "Strict necesare", necessaryDesc: "Necesare pentru autentificare, securitate și salvarea alegerii tale.", alwaysOn: "Mereu active",
    analytics: "Analiză", analyticsDesc: "Ne ajută să îmbunătățim produsul.",
    marketing: "Marketing", marketingDesc: "Măsoară campaniile și relevanța.",
    acceptAll: "Acceptă tot", rejectAll: "Respinge opționalele", save: "Salvează alegerile", customise: "Personalizează",
  },
};

/** The RAW copy — proof and coverage tokens unfilled. The gates read this
 *  to prove no accuracy number is typed; nothing renders it directly. */
export const LANDING_STRINGS: Record<string, LandingStrings> = { en, ro };

const FILLED: Record<string, LandingStrings> = {};

/** The copy for a language, every `{proof…}` / `{coverage…}` token filled
 *  from engineProof.json and coverage.json in that language's number and
 *  date format. An unknown token throws (lib/engineProof.fillProof). */
export function landingStringsFor(langCode: string): LandingStrings {
  const code = LANDING_STRINGS[langCode] ? langCode : "en";
  return (FILLED[code] ??= fillProofDeep(LANDING_STRINGS[code], code));
}
