// The /sample page's own words, in both languages.
//
// Kept beside the page (like landingStrings.ts beside the landing) and NOT
// in the i18n locale files: the page is public, loads before any app
// surface does, and its copy is reviewed as one piece.
//
// WHAT IS NOT HERE. No measured figure, no count, no date and no engine
// sentence. Every number the page prints is read from
// frontend/data/publicSample.json
// (generated by scripts/build_public_sample.py from the served documents), and
// the engine's sentences are quoted from that file verbatim. A sentence
// below that needs a figure takes it as a `{placeholder}`.
//
// Romanian: informal tu-form, comma-below diacritics.

import type { FileKey, SampleLang } from "@/lib/publicSample";

export interface SampleStrings {
  metaTitle: string;
  metaDescription: string;
  home: string;
  otherLanguage: string;
  eyebrow: string;
  title: string;
  /** {company} */
  lede: string;
  fictionalTitle: string;
  /** {fiscalCode} {tradeRegister} */
  fictionalBody: string;
  facts: { activity: string; years: string; accounts: string; asOf: string };
  /** {current} {prior} */
  yearsValue: string;
  /** {n} {period} */
  accountsValue: string;

  downloadsTitle: string;
  downloadsLede: string;
  download: string;
  open: string;
  /** {size} */
  sizeKb: string;
  files: Record<FileKey, { title: string; body: string }>;

  figuresTitle: string;
  figuresLede: string;
  figure: string;
  figures: Record<string, string>;
  ratiosTitle: string;
  ratiosLede: string;
  ratio: string;

  verdictsTitle: string;
  verdictsLede: string;
  verdict: {
    balanceTitle: string;
    /** {status} {assets} {liabilities} {difference} */
    balanceBody: string;
    /** {n} */
    balanceSource: string;
    anchorTitle: string;
    /** {value} */
    anchorBody: string;
    /** {reconstructed} {variation} */
    anchorBridge: string;
    variationTitle: string;
    /** {value} */
    variationBody: string;
    ebitdaTitle: string;
    /** {value} */
    ebitdaBody: string;
    /** {difference} */
    ebitdaVariants: string;
    ebitdaVariantNames: Record<string, string>;
    creditTitle: string;
    /** {letter} {composite} {z} {zone} */
    creditBody: string;
    zones: Record<string, string>;
    inventoryTitle: string;
    /** {days} {basis} */
    inventoryBody: string;
    inventorySeasonal: string;
    cashFlowTitle: string;
    cashFlowApproximated: string;
    cashFlowExact: string;
    findingsTitle: string;
    /** {n} */
    findingsBody: string;
    levels: Record<string, string>;
    findingsEnglish: string;
  };

  labelsTitle: string;
  /** {n} */
  labelsLede: string;
  engineWords: string;
  engineWordsEnglishOnly: string;
  kinds: Record<string, string>;
  areas: Record<string, string>;
  labelTitles: Record<string, string>;
  /** The title of an insight the engine checked and did not raise, for an
   *  id this table does not name. {id} */
  labelNotFiredFallback: string;
  /** {ratio} */
  labelRatioRefused: string;

  mappingTitle: string;
  /** {n} */
  mappingLede: string;
  mappingColumns: { account: string; name: string; line: string; amount: string };
  statements: Record<string, string>;
  buckets: Record<string, string>;
  sections: Record<string, string>;
  mappingStatus: Record<string, string>;
  /** {value} */
  mappingNoteDerived: string;
  /** {n} */
  showAll: string;
  showFewer: string;

  howTitle: string;
  howSteps: string[];
  howGate: string;
  engineTitle: string;
  engine: Record<string, string>;
  notIncludedTitle: string;
  notIncluded: string[];

  ctaTitle: string;
  ctaBody: string;
  ctaPrimary: string;
  ctaSecondary: string;
}

const EN: SampleStrings = {
  metaTitle: "Public sample: a fictional company, read by the engine · CFO AI",
  metaDescription:
    "A fictional Romanian company's trial balance, the complete report the engine produces from it, the mapping of every account and each uncertainty label. No sign-in.",
  home: "Home",
  otherLanguage: "Română",
  eyebrow: "Public sample · fictional data",
  title: "A fictional company, read by the real engine",
  lede:
    "{company} does not exist. A script wrote its two trial balances, and the same engine that reads an uploaded trial balance processed them offline, with no AI model. Everything it produced is on this page: the files, the complete report, the mapping of every account and each uncertainty label it raised.",
  fictionalTitle: "Fictional data, never a client book",
  fictionalBody:
    "No client trial balance was used here, anonymised or otherwise. The fiscal code {fiscalCode} fails the Romanian checksum on purpose, so it can match no real company, and the trade-register number {tradeRegister} does not exist.",
  facts: {
    activity: "Activity",
    years: "Financial years",
    accounts: "Accounts",
    asOf: "Generated",
  },
  yearsValue: "{current} and {prior}",
  accountsValue: "{n} in {period}",

  downloadsTitle: "Download and inspect",
  downloadsLede:
    "Open the trial balance, read the report, then check one against the other. Nothing here needs an account.",
  download: "Download",
  open: "Open",
  sizeKb: "{size} KB",
  files: {
    trial_balance_current: {
      title: "Trial balance, current year (Excel)",
      body: "The file the engine read: Romanian chart of accounts, 10-column layout, closed into account 121.",
    },
    trial_balance_prior: {
      title: "Trial balance, prior year (Excel)",
      body: "The current year opens with these closing balances, account by account.",
    },
    report_html: {
      title: "Complete report (HTML)",
      body: "The product's own export, exactly as a signed-in user downloads it. The exported report is in English.",
    },
    report_pdf: {
      title: "Complete report (PDF)",
      body: "The same document, printed to A4.",
    },
    mapping: {
      title: "Account mapping (CSV)",
      body: "Every account and the statement line the engine assigned it to.",
    },
    labels: {
      title: "Uncertainty labels (JSON)",
      body: "Each approximation, derivation, basis and refusal, in the engine's own words.",
    },
    served_current: {
      title: "Served document, current year (JSON)",
      body: "What the engine's API returned for the period. Every figure on this page is read from it.",
    },
    served_prior: {
      title: "Served document, prior year (JSON)",
      body: "The same, for the prior year.",
    },
    served_comparatives: {
      title: "Served comparison (JSON)",
      body: "The two years side by side, as the engine compares them.",
    },
  },

  figuresTitle: "What the engine read",
  figuresLede: "Headline figures of both years, in RON, as served.",
  figure: "Figure",
  figures: {
    net_turnover: "Net turnover (cifra de afaceri)",
    ebitda: "EBITDA",
    operating_result: "Operating result",
    net_income_statutory: "Net profit (account 121)",
    stock_variation_711: "Stock variation (account 711)",
    net_provisions: "Net provisions and impairment adjustments",
    total_assets: "Total assets",
    total_equity: "Equity",
    total_liabilities: "Total liabilities",
    cash: "Cash and bank",
    total_debt: "Bank and lease debt",
  },
  ratiosTitle: "Ratios and credit",
  ratiosLede: "Printed at the engine's own precision, with the band it graded each one into.",
  ratio: "Ratio",

  verdictsTitle: "The engine's verdicts on this book",
  verdictsLede: "Copied from the served document. None of these is decided by this page.",
  verdict: {
    balanceTitle: "Balance sheet",
    balanceBody:
      "{status}: assets {assets}, equity plus liabilities {liabilities}, difference {difference}.",
    balanceSource: "The file's own totals row matches what was read. Accounts left unmapped: {n}.",
    anchorTitle: "Net profit and account 121",
    anchorBody: "The served net profit is the closing balance of account 121: {value}.",
    anchorBridge:
      "Rebuilt from the other accounts, the result reaches {reconstructed}; the step to account 121 is the stock variation, {variation}.",
    variationTitle: "Stock variation (711)",
    variationBody:
      "{value}, derived and not read: a closed trial balance keeps no net balance on account 711, so the engine derives it from account 121 under its guards.",
    ebitdaTitle: "EBITDA",
    ebitdaBody: "{value}, stock variation included.",
    ebitdaVariants:
      "Three named variants are each computed twice, by the methodology layer and by the engine's own code. Largest difference between the two here: {difference}.",
    ebitdaVariantNames: { reported: "reported", strict: "strict", cash: "cash" },
    creditTitle: "Credit",
    creditBody: "{letter}, composite {composite} of 100. Altman Z″ {z}: {zone}.",
    zones: { safe: "safe zone", grey: "grey zone", distress: "distress zone" },
    inventoryTitle: "Inventory days",
    inventoryBody: "{days}, on this basis: {basis}.",
    inventorySeasonal: "Flagged as seasonal for a food manufacturer.",
    cashFlowTitle: "Cash flow",
    cashFlowApproximated:
      "Approximated, and labelled so on the statement itself. See the uncertainty labels below.",
    cashFlowExact: "Reconstructed from both years' balances.",
    findingsTitle: "Findings",
    findingsBody: "{n} findings, by severity:",
    levels: {
      critical: "critical",
      high: "high",
      medium: "medium",
      low: "low",
      info: "informational",
    },
    findingsEnglish: "The engine writes its findings in English.",
  },

  labelsTitle: "Uncertainty labels",
  labelsLede:
    "{n} notes the engine attached to this book: what is approximated, derived, on a stated basis, refused or not assessed, and what it checked and found clear.",
  engineWords: "The engine's words",
  engineWordsEnglishOnly: "The engine's words (it has this sentence in English only)",
  kinds: {
    approximation: "Approximation",
    derived: "Derived",
    basis: "Basis",
    refusal: "Refusal",
    not_assessed: "Not assessed",
    checked_clear: "Checked, clear",
  },
  areas: {
    cash_flow: "Cash flow",
    profit_and_loss: "Profit and loss",
    ratios: "Ratios",
    risk: "Risk",
    findings: "Findings",
    document: "Document",
    comparison: "Comparison",
  },
  labelTitles: {
    cash_flow_approximated_1: "Working-capital movements are estimated",
    cash_flow_approximated_2: "Financing detail is approximated",
    stock_variation_derived: "The stock variation (711) is derived from account 121",
    stock_variation_identity: "The reconciliation to account 121 closes by construction",
    stock_variation_refused: "The stock variation (711) cannot be measured",
    ebitda_refused: "EBITDA is refused",
    inventory_days_basis: "Inventory days use the average of two year-end balances",
    inventory_days_seasonality: "Year-end stock is seasonal in this activity",
    inventory_days_claim_policy: "What may be said about the stock",
    piotroski_prior_unavailable: "Piotroski: the year-over-year checks are not assessed",
    insight_not_fired_reconstruction_gap: "Reconstruction gap: checked, nothing to raise",
    insight_not_fired_related_party_exposure: "Related-party balances: checked, none in the book",
    insight_not_fired_unclassified_balances: "Unclassified balances: checked, none in the book",
    calibration_tier: "Calibration tier of the country pack",
    detail_level: "The book is read at synthetic-account depth",
    comparison_level: "The two years are compared at synthetic level",
  },
  labelNotFiredFallback: "Checked, nothing to raise ({id})",
  labelRatioRefused: "Refused ratio: {ratio}",

  mappingTitle: "Account mapping",
  mappingLede:
    "All {n} accounts of the current year's trial balance, and the line the engine assigned each one to.",
  mappingColumns: { account: "Account", name: "Name", line: "Engine line", amount: "Amount carried (RON)" },
  statements: { BS: "Balance sheet", PL: "Profit and loss" },
  buckets: {
    shareCapital: "Share capital",
    otherEquity: "Reserves",
    retainedEarnings: "Retained earnings",
    ltDebt: "Long-term debt",
    stDebt: "Short-term bank debt",
    otherNonCurrentLiab: "Provisions and deferred income",
    ap: "Trade payables",
    otherCurrentLiab: "Other current liabilities",
    ppe: "Property, plant and equipment",
    intangibles: "Intangible assets",
    inventory: "Inventory",
    ar: "Trade receivables",
    otherCurrentAssets: "Other current assets",
    cash: "Cash and bank",
    revenue: "Revenue (turnover)",
    cogs: "Cost of materials and goods",
    operatingExpenses: "Operating expenses",
    depreciation: "Depreciation, provisions and adjustments",
    otherIncome: "Other operating income",
    financialIncome: "Financial income",
    financialExpense: "Financial expense",
    interestExpense: "Interest expense",
    taxExpense: "Income tax",
  },
  sections: {
    non_current_assets: "non-current assets",
    current_assets: "current assets",
    prepaid_expenses: "prepaid expenses",
    equity: "equity",
    provisions: "provisions",
    non_current_liabilities: "non-current liabilities",
    current_liabilities: "current liabilities",
    deferred_income: "deferred income",
  },
  mappingStatus: {
    "excluded:profit_control_account_121":
      "Not summed as an account: its closing balance is taken as the statutory net profit.",
    "excluded:transit_account_581": "Transit account, excluded from the statements.",
    no_closing_balance: "Closes at zero: nothing is carried to the statements.",
  },
  mappingNoteDerived:
    "The amount is the account's gross turnover. The line the engine serves in the P&L is the derived net: {value}.",
  showAll: "Show all {n} accounts",
  showFewer: "Show fewer",

  howTitle: "How this sample is made",
  howSteps: [
    "scripts/build_public_sample_tb.py writes the two trial balances from a double-entry ledger: fixed seed, no clock.",
    "scripts/build_public_sample.py carries them through the engine offline: the production parse, mapping and persist path, served by the real API application over a database double, with the network blocked and no model.",
    "scripts/build_public_sample_report.mjs builds the report with the product's own report builder and prints the PDF.",
  ],
  howGate:
    "A release gate (public-sample) rebuilds everything and fails when a published file differs from the rebuild.",
  engineTitle: "Engine that produced it",
  engine: {
    parser_version: "Trial-balance parser",
    extraction_method: "Reading",
    mapping_version: "Account mapping",
    ebitda_definition: "EBITDA definition",
    credit_model_revision: "Credit model revision",
    canonical_version: "Served document version",
  },
  notIncludedTitle: "Not in this sample",
  notIncluded: [
    "The narrative briefing. In the product it is written by an AI model; this sample is built without one.",
    "The valuation view of the signed-in report page.",
    "Sector benchmarks from public filings.",
  ],

  ctaTitle: "Try it on your own trial balance",
  ctaBody: "Upload a trial balance and you get the same kind of report as the one on this page.",
  ctaPrimary: "Create an account",
  ctaSecondary: "Back to the home page",
};

const RO: SampleStrings = {
  metaTitle: "Exemplu public: o firmă fictivă, citită de motor · CFO AI",
  metaDescription:
    "Balanța de verificare a unei firme românești fictive, raportul complet pe care motorul îl produce din ea, maparea fiecărui cont și fiecare etichetă de incertitudine. Fără cont.",
  home: "Acasă",
  otherLanguage: "English",
  eyebrow: "Exemplu public · date fictive",
  title: "O firmă fictivă, citită de motorul real",
  lede:
    "{company} nu există. Un script i-a scris cele două balanțe de verificare, iar același motor care citește o balanță încărcată le-a procesat offline, fără niciun model AI. Tot ce a produs este pe pagina aceasta: fișierele, raportul complet, maparea fiecărui cont și fiecare etichetă de incertitudine pe care a ridicat-o.",
  fictionalTitle: "Date fictive, niciodată balanța unui client",
  fictionalBody:
    "Aici nu a fost folosită nicio balanță de client, anonimizată sau nu. Codul fiscal {fiscalCode} nu trece intenționat de cifra de control, deci nu poate corespunde niciunei firme reale, iar numărul de la registrul comerțului {tradeRegister} nu există.",
  facts: {
    activity: "Activitate",
    years: "Exerciții financiare",
    accounts: "Conturi",
    asOf: "Generat",
  },
  yearsValue: "{current} și {prior}",
  accountsValue: "{n} în {period}",

  downloadsTitle: "Descarcă și verifică",
  downloadsLede:
    "Deschide balanța, citește raportul, apoi verifică una cu cealaltă. Nimic de aici nu cere cont.",
  download: "Descarcă",
  open: "Deschide",
  sizeKb: "{size} KB",
  files: {
    trial_balance_current: {
      title: "Balanța de verificare, anul curent (Excel)",
      body: "Fișierul pe care l-a citit motorul: plan de conturi românesc, format cu 10 coloane, închis în contul 121.",
    },
    trial_balance_prior: {
      title: "Balanța de verificare, anul precedent (Excel)",
      body: "Anul curent se deschide cu aceste solduri finale, cont cu cont.",
    },
    report_html: {
      title: "Raportul complet (HTML)",
      body: "Exportul produsului, exact cum îl descarcă un utilizator autentificat. Raportul exportat este în engleză.",
    },
    report_pdf: {
      title: "Raportul complet (PDF)",
      body: "Același document, tipărit pe A4.",
    },
    mapping: {
      title: "Maparea conturilor (CSV)",
      body: "Fiecare cont și linia din situații pe care i-a atribuit-o motorul.",
    },
    labels: {
      title: "Etichete de incertitudine (JSON)",
      body: "Fiecare aproximare, derivare, bază de calcul și refuz, în cuvintele motorului.",
    },
    served_current: {
      title: "Documentul servit, anul curent (JSON)",
      body: "Ce a returnat API-ul motorului pentru perioadă. Fiecare cifră de pe pagina aceasta este citită din el.",
    },
    served_prior: {
      title: "Documentul servit, anul precedent (JSON)",
      body: "Același lucru, pentru anul precedent.",
    },
    served_comparatives: {
      title: "Comparația servită (JSON)",
      body: "Cei doi ani unul lângă altul, așa cum îi compară motorul.",
    },
  },

  figuresTitle: "Ce a citit motorul",
  figuresLede: "Cifrele principale ale ambilor ani, în RON, așa cum au fost servite.",
  figure: "Indicator",
  figures: {
    net_turnover: "Cifra de afaceri netă",
    ebitda: "EBITDA",
    operating_result: "Rezultatul din exploatare",
    net_income_statutory: "Profit net (contul 121)",
    stock_variation_711: "Variația stocurilor (contul 711)",
    net_provisions: "Provizioane și ajustări nete",
    total_assets: "Total active",
    total_equity: "Capitaluri proprii",
    total_liabilities: "Total datorii",
    cash: "Casa și conturi la bănci",
    total_debt: "Credite bancare și leasing",
  },
  ratiosTitle: "Indicatori și credit",
  ratiosLede: "Tipăriți la precizia motorului, cu banda în care l-a încadrat pe fiecare.",
  ratio: "Indicator",

  verdictsTitle: "Verdictele motorului pentru această balanță",
  verdictsLede: "Copiate din documentul servit. Pagina aceasta nu decide niciunul.",
  verdict: {
    balanceTitle: "Bilanț",
    balanceBody:
      "{status}: active {assets}, capitaluri proprii plus datorii {liabilities}, diferență {difference}.",
    balanceSource: "Rândul de totaluri din fișier corespunde cu ce a fost citit. Conturi rămase nemapate: {n}.",
    anchorTitle: "Profitul net și contul 121",
    anchorBody: "Profitul net servit este soldul final al contului 121: {value}.",
    anchorBridge:
      "Reconstruit din celelalte conturi, rezultatul ajunge la {reconstructed}; pasul până la contul 121 este variația stocurilor, {variation}.",
    variationTitle: "Variația stocurilor (711)",
    variationBody:
      "{value}, derivată, nu citită: o balanță închisă nu păstrează soldul net al contului 711, așa că motorul o derivă din contul 121, sub condițiile lui de siguranță.",
    ebitdaTitle: "EBITDA",
    ebitdaBody: "{value}, cu variația stocurilor inclusă.",
    ebitdaVariants:
      "Trei variante denumite sunt calculate fiecare de două ori, de stratul de metodologie și de codul motorului. Cea mai mare diferență dintre cele două, aici: {difference}.",
    ebitdaVariantNames: { reported: "raportat", strict: "strict", cash: "numerar" },
    creditTitle: "Credit",
    creditBody: "{letter}, scor compus {composite} din 100. Altman Z″ {z}: {zone}.",
    zones: { safe: "zona sigură", grey: "zona gri", distress: "zona de dificultate" },
    inventoryTitle: "Zile de stoc",
    inventoryBody: "{days}, pe această bază: {basis}.",
    inventorySeasonal: "Semnalat ca sezonier pentru un producător din industria alimentară.",
    cashFlowTitle: "Fluxul de numerar",
    cashFlowApproximated:
      "Aproximat, și etichetat astfel chiar pe situație. Vezi etichetele de incertitudine de mai jos.",
    cashFlowExact: "Reconstruit din soldurile ambilor ani.",
    findingsTitle: "Constatări",
    findingsBody: "{n} constatări, după severitate:",
    levels: {
      critical: "critice",
      high: "ridicate",
      medium: "medii",
      low: "scăzute",
      info: "informative",
    },
    findingsEnglish: "Motorul își formulează constatările în engleză.",
  },

  labelsTitle: "Etichete de incertitudine",
  labelsLede:
    "{n} note pe care motorul le-a atașat acestei balanțe: ce este aproximat, derivat, calculat pe o bază declarată, refuzat sau neevaluat și ce a verificat fără să găsească nimic.",
  engineWords: "Cuvintele motorului",
  engineWordsEnglishOnly: "Cuvintele motorului (are această frază doar în engleză)",
  kinds: {
    approximation: "Aproximare",
    derived: "Derivat",
    basis: "Bază de calcul",
    refusal: "Refuz",
    not_assessed: "Neevaluat",
    checked_clear: "Verificat, fără semnal",
  },
  areas: {
    cash_flow: "Flux de numerar",
    profit_and_loss: "Cont de profit și pierdere",
    ratios: "Indicatori",
    risk: "Risc",
    findings: "Constatări",
    document: "Document",
    comparison: "Comparație",
  },
  labelTitles: {
    cash_flow_approximated_1: "Mișcările de capital de lucru sunt estimate",
    cash_flow_approximated_2: "Detaliul finanțării este aproximat",
    stock_variation_derived: "Variația stocurilor (711) este derivată din contul 121",
    stock_variation_identity: "Reconcilierea cu contul 121 se închide prin construcție",
    stock_variation_refused: "Variația stocurilor (711) nu poate fi măsurată",
    ebitda_refused: "EBITDA este refuzat",
    inventory_days_basis: "Zilele de stoc folosesc media a două solduri de sfârșit de an",
    inventory_days_seasonality: "Stocul de la sfârșit de an este sezonier în această activitate",
    inventory_days_claim_policy: "Ce se poate afirma despre stoc",
    piotroski_prior_unavailable: "Piotroski: verificările față de anul precedent nu sunt evaluate",
    insight_not_fired_reconstruction_gap: "Diferența de reconstrucție: verificată, nimic de semnalat",
    insight_not_fired_related_party_exposure: "Solduri cu părți afiliate: verificate, niciunul în balanță",
    insight_not_fired_unclassified_balances: "Solduri neclasificate: verificate, niciunul în balanță",
    calibration_tier: "Nivelul de calibrare al pachetului de țară",
    detail_level: "Balanța este citită la nivel de conturi sintetice",
    comparison_level: "Cei doi ani sunt comparați la nivel sintetic",
  },
  labelNotFiredFallback: "Verificat, nimic de semnalat ({id})",
  labelRatioRefused: "Indicator refuzat: {ratio}",

  mappingTitle: "Maparea conturilor",
  mappingLede:
    "Toate cele {n} conturi din balanța anului curent și linia pe care motorul a atribuit-o fiecăruia.",
  mappingColumns: { account: "Cont", name: "Denumire", line: "Linia motorului", amount: "Sumă preluată (RON)" },
  statements: { BS: "Bilanț", PL: "Cont de profit și pierdere" },
  buckets: {
    shareCapital: "Capital social",
    otherEquity: "Rezerve",
    retainedEarnings: "Rezultat reportat",
    ltDebt: "Datorii pe termen lung",
    stDebt: "Credite bancare pe termen scurt",
    otherNonCurrentLiab: "Provizioane și venituri în avans",
    ap: "Furnizori",
    otherCurrentLiab: "Alte datorii curente",
    ppe: "Imobilizări corporale",
    intangibles: "Imobilizări necorporale",
    inventory: "Stocuri",
    ar: "Clienți",
    otherCurrentAssets: "Alte active curente",
    cash: "Casa și conturi la bănci",
    revenue: "Venituri (cifra de afaceri)",
    cogs: "Costul materialelor și mărfurilor",
    operatingExpenses: "Cheltuieli de exploatare",
    depreciation: "Amortizare, provizioane și ajustări",
    otherIncome: "Alte venituri din exploatare",
    financialIncome: "Venituri financiare",
    financialExpense: "Cheltuieli financiare",
    interestExpense: "Cheltuieli cu dobânzile",
    taxExpense: "Impozit pe profit",
  },
  sections: {
    non_current_assets: "active imobilizate",
    current_assets: "active circulante",
    prepaid_expenses: "cheltuieli în avans",
    equity: "capitaluri proprii",
    provisions: "provizioane",
    non_current_liabilities: "datorii pe termen lung",
    current_liabilities: "datorii curente",
    deferred_income: "venituri în avans",
  },
  mappingStatus: {
    "excluded:profit_control_account_121":
      "Nu este însumat ca un cont obișnuit: soldul lui final este luat drept profitul net statutar.",
    "excluded:transit_account_581": "Cont de tranzit, exclus din situații.",
    no_closing_balance: "Se închide pe zero: nimic nu este preluat în situații.",
  },
  mappingNoteDerived:
    "Suma este rulajul brut al contului. Linia pe care motorul o servește în contul de profit și pierdere este valoarea netă derivată: {value}.",
  showAll: "Arată toate cele {n} conturi",
  showFewer: "Arată mai puține",

  howTitle: "Cum este făcut acest exemplu",
  howSteps: [
    "scripts/build_public_sample_tb.py scrie cele două balanțe dintr-un registru în partidă dublă: sămânță fixă, fără ceas.",
    "scripts/build_public_sample.py le trece prin motor offline: calea de producție pentru citire, mapare și salvare, servită de aplicația API reală peste o dublură a bazei de date, cu rețeaua blocată și fără model.",
    "scripts/build_public_sample_report.mjs construiește raportul cu generatorul de rapoarte al produsului și tipărește PDF-ul.",
  ],
  howGate:
    "O verificare de lansare (public-sample) reconstruiește totul și pică atunci când un fișier publicat diferă de reconstrucție.",
  engineTitle: "Motorul care l-a produs",
  engine: {
    parser_version: "Cititorul de balanțe",
    extraction_method: "Citire",
    mapping_version: "Maparea conturilor",
    ebitda_definition: "Definiția EBITDA",
    credit_model_revision: "Revizia modelului de credit",
    canonical_version: "Versiunea documentului servit",
  },
  notIncludedTitle: "Ce nu conține acest exemplu",
  notIncluded: [
    "Rezumatul narativ. În produs îl scrie un model AI; exemplul acesta este construit fără niciun model.",
    "Secțiunea de evaluare din pagina de raport pentru utilizatori autentificați.",
    "Comparațiile cu sectorul, din situațiile financiare publice.",
  ],

  ctaTitle: "Încearcă cu propria ta balanță",
  ctaBody: "Încarci o balanță de verificare și primești același tip de raport ca cel de pe pagina aceasta.",
  ctaPrimary: "Creează un cont",
  ctaSecondary: "Înapoi la pagina principală",
};

export function sampleStringsFor(language: string | null | undefined): SampleStrings {
  return sampleLangOf(language) === "ro" ? RO : EN;
}

export function sampleLangOf(language: string | null | undefined): SampleLang {
  return (language ?? "").toLowerCase().startsWith("ro") ? "ro" : "en";
}

/** `{name}` placeholders filled from `values`; an unfilled placeholder is
 *  a bug in the caller and stays visible. */
export function fill(template: string, values: Record<string, string>): string {
  return template.replace(/\{(\w+)\}/g, (whole, name: string) =>
    Object.prototype.hasOwnProperty.call(values, name) ? values[name] : whole,
  );
}

export const SAMPLE_STRINGS: Record<SampleLang, SampleStrings> = { en: EN, ro: RO };
