// F5.0 Phase 1+ — Concept pack for the 3 statement views.
//
// Covers Cash Flow / P&L / Balance Sheet most-visible lines. Phase 4 will
// split this further by category (cash_flow.ts / profitability.ts /
// balance_sheet.ts) and add 30-50 more concepts; this file gets the proof
// rollout working end-to-end across every statement view today.
//
// Concepts here are paired with each `<LearnableNumber>` wrap inside the
// 3 statement view components (`CashFlowStatementView`, `PLStatementView`,
// `BSStatementView`) + the 4 KpiTiles in FinancialStatements.

import type { Concept } from "./_schema";

// ─── Cash Flow concepts ───────────────────────────────────────────────────

const net_profit: Concept = {
  key: "net_profit",
  name: { en: "Net Profit", ro: "Profit net" },
  category: "Cash Flow",
  shortDefinition: {
    en: "The bottom-line profit of the period — revenue minus every expense, " +
        "interest, and tax. The starting point of the indirect cash-flow method.",
    ro: "Profitul de la baza contului de profit și pierdere — venituri minus toate " +
        "cheltuielile, dobânzile și impozitul. Punctul de plecare al metodei indirecte.",
  },
  inlineFormula: "EBIT + Net Financial − Tax",
  plainEnglish: {
    en: "What the business actually kept after paying everything. " +
        "If positive, this flows to retained earnings on the balance sheet.",
    ro: "Ce a păstrat efectiv afacerea după plata tuturor cheltuielilor. " +
        "Dacă e pozitiv, intră în profitul reportat din bilanț.",
  },
  related: ["ebitda", "operating_cash_flow", "income_tax"],
};

const depreciation_amortization: Concept = {
  key: "depreciation_amortization",
  name: { en: "Depreciation & Amortization", ro: "Amortizare" },
  category: "Cash Flow",
  shortDefinition: {
    en: "Non-cash expense reflecting the gradual write-down of fixed assets " +
        "and intangibles. Added back to net profit because it never left as cash.",
    ro: "Cheltuială non-cash care reflectă deprecierea graduală a activelor " +
        "fixe și a intangibilelor. Se adaugă înapoi la profit pentru că nu a fost cash.",
  },
  inlineFormula: "Σ Account 681 (depreciation expense)",
  related: ["net_profit", "operating_cash_flow", "ppe", "capex"],
  computation: (ctx, value) => {
    const trace = ctx.metrics?.accountTraces?.["depreciation_amortization"] ?? [];
    return {
      result: { value, format: "currency", conceptKey: "depreciation_amortization" },
      layout: "stacked",
      tokens: [],
      trace: trace.length > 0 ? { accounts: trace } : undefined,
    };
  },
};

const operating_cash_flow_before_wc: Concept = {
  key: "operating_cash_flow_before_wc",
  name: { en: "Operating CF Before WC Changes", ro: "CF operațional înainte de modificări WC" },
  category: "Cash Flow",
  shortDefinition: {
    en: "Cash generated by operations before adjusting for working-capital " +
        "movements. Approximates the cash earning power if A/R, A/P, and " +
        "inventory stayed flat.",
    ro: "Cash generat de operațiuni înainte de ajustarea pentru modificările " +
        "capitalului de lucru. Aproximează capacitatea de cash dacă creanțele, " +
        "datoriile și stocul ar rămâne neschimbate.",
  },
  inlineFormula: "Net Profit + D&A",
  related: ["net_profit", "operating_cash_flow", "working_capital_changes"],
};

const working_capital_changes: Concept = {
  key: "working_capital_changes",
  name: { en: "Working Capital Changes", ro: "Modificări capital de lucru" },
  category: "Cash Flow",
  shortDefinition: {
    en: "Cash consumed by — or released from — movements in receivables, " +
        "inventory, and payables. Negative means cash was absorbed into " +
        "working capital; positive means working capital released cash.",
    ro: "Cash consumat sau eliberat prin modificarea creanțelor, stocurilor " +
        "și datoriilor. Negativ înseamnă cash absorbit; pozitiv înseamnă cash eliberat.",
  },
  inlineFormula: "−Δ AR − Δ Inventory + Δ AP",
  related: ["operating_cash_flow", "receivables", "inventory", "dpo_days", "dso_days", "dio_days"],
};

const operating_cash_flow: Concept = {
  key: "operating_cash_flow",
  name: { en: "Cash from Operating Activities", ro: "Cash din activitatea operațională" },
  category: "Cash Flow",
  shortDefinition: {
    en: "Total cash generated by the operating business in the period. The " +
        "purest read on operating performance after working-capital reality. " +
        "Should be positive and stable for a healthy business.",
    ro: "Total cash generat de activitatea operațională în perioadă. Cea mai " +
        "curată citire a performanței operaționale după realitatea capitalului " +
        "de lucru. Trebuie să fie pozitivă și stabilă la o companie sănătoasă.",
  },
  inlineFormula: "Net Profit + D&A + ΔWC",
  plainEnglish: {
    en: "Cash the business actually generated from running day-to-day. " +
        "Different from profit — profit can be inflated by booking receivables. " +
        "Cash is cash.",
    ro: "Cash-ul efectiv generat din activitatea zilnică. Diferit de profit — " +
        "profitul poate fi umflat de creanțe nenecasate. Cash-ul e cash.",
  },
  computation: (ctx, value) => {
    const m = ctx.metrics ?? {};
    return {
      result: { value, format: "currency" },
      layout: "stacked",
      tokens: [
        { type: "value", value: m.netProfit ?? 0, conceptKey: "net_profit", label: "Net Profit", format: "currency" },
        { type: "operator", op: "+" },
        { type: "value", value: m.depreciation ?? 0, conceptKey: "depreciation_amortization", label: "D&A", format: "currency" },
        { type: "operator", op: "+" },
        { type: "value", value: m.workingCapitalChanges ?? 0, conceptKey: "working_capital_changes", label: "ΔWC", format: "currency" },
      ],
    };
  },
  interpretation: {
    getSentiment: (value) => {
      if (value < 0) return "negative";
      if (value > 0) return "positive";
      return "neutral";
    },
    getNarrative: (value) => {
      if (value < 0) {
        return "Negative — the operating business consumed cash this period. Investigate why.";
      }
      if (value > 0) {
        return "Positive — operating activities are generating cash, the core test of a healthy business.";
      }
      return "Approximately break-even — operating cash flow neither generated nor consumed cash materially.";
    },
  },
  related: ["net_profit", "depreciation_amortization", "working_capital_changes", "free_cash_flow"],
};

const capex: Concept = {
  key: "capex",
  name: { en: "Capital Expenditure", ro: "Investiții (CAPEX)" },
  category: "Cash Flow",
  shortDefinition: {
    en: "Cash spent acquiring or upgrading long-lived assets — equipment, " +
        "buildings, intangibles. The maintenance + growth investment in the " +
        "asset base.",
    ro: "Cash cheltuit pe achiziția sau modernizarea activelor pe termen lung — " +
        "echipamente, clădiri, intangibile. Investiția de mentenanță plus creștere " +
        "în baza de active.",
  },
  inlineFormula: "Δ Gross PP&E + Δ Intangibles",
  related: ["depreciation_amortization", "ppe", "investing_cash_flow", "free_cash_flow"],
};

const investing_cash_flow: Concept = {
  key: "investing_cash_flow",
  name: { en: "Cash from Investing", ro: "Cash din activitatea de investiții" },
  category: "Cash Flow",
  shortDefinition: {
    en: "Net cash from buying/selling long-term assets and investments. Almost " +
        "always negative for a growing business (it's reinvesting); positive " +
        "can mean divestments.",
    ro: "Cash net din cumpărarea/vânzarea activelor pe termen lung. Aproape " +
        "întotdeauna negativ pentru o companie în creștere; pozitiv poate însemna " +
        "vânzări de active.",
  },
  related: ["capex", "operating_cash_flow", "financing_cash_flow"],
};

const lt_debt_drawdowns: Concept = {
  key: "lt_debt_drawdowns",
  name: { en: "Long-Term Debt Drawdowns", ro: "Trageri credit pe termen lung" },
  category: "Cash Flow",
  shortDefinition: {
    en: "Cash received from new long-term bank loans during the period. " +
        "Positive financing inflow.",
    ro: "Cash primit din credite noi pe termen lung în perioadă. Intrare " +
        "pozitivă în activitatea de finanțare.",
  },
  inlineFormula: "Σ Account 1621 credit movements",
  related: ["financing_cash_flow", "lt_debt_repayments", "interest_coverage"],
};

const lt_debt_repayments: Concept = {
  key: "lt_debt_repayments",
  name: { en: "Long-Term Debt Repayments", ro: "Rambursări credit pe termen lung" },
  category: "Cash Flow",
  shortDefinition: {
    en: "Principal repayments on long-term bank loans during the period. " +
        "Cash outflow.",
    ro: "Rambursări de principal la credite pe termen lung în perioadă. " +
        "Ieșire de cash.",
  },
  inlineFormula: "Σ Account 1621 debit movements",
  related: ["lt_debt_drawdowns", "financing_cash_flow", "interest_coverage"],
};

const dividends_paid: Concept = {
  key: "dividends_paid",
  name: { en: "Dividends Paid", ro: "Dividende plătite" },
  category: "Cash Flow",
  shortDefinition: {
    en: "Cash actually distributed to shareholders in the period. Different " +
        "from dividends DECLARED — declared dividends sit in account 457 " +
        "until cash leaves.",
    ro: "Cash efectiv distribuit acționarilor în perioadă. Diferit de dividende " +
        "DECLARATE — cele declarate stau în contul 457 până când cash-ul iese.",
  },
  related: ["net_profit", "financing_cash_flow"],
};

const financing_cash_flow: Concept = {
  key: "financing_cash_flow",
  name: { en: "Cash from Financing", ro: "Cash din activitatea de finanțare" },
  category: "Cash Flow",
  shortDefinition: {
    en: "Net cash from financing activities — debt draws minus repayments, " +
        "minus dividends paid, plus equity issued. Tells you how the business " +
        "is funded.",
    ro: "Cash net din activitatea de finanțare — trageri minus rambursări, " +
        "minus dividende plătite, plus emisiuni de capital. Spune cum este finanțat.",
  },
  related: ["operating_cash_flow", "investing_cash_flow", "lt_debt_drawdowns", "dividends_paid"],
};

const net_change_in_cash: Concept = {
  key: "net_change_in_cash",
  name: { en: "Net Change in Cash", ro: "Modificare netă cash" },
  category: "Cash Flow",
  shortDefinition: {
    en: "The bottom line of the cash flow statement — how much cash grew or " +
        "shrank during the period. Operating + Investing + Financing.",
    ro: "Linia de jos a contului de cash flow — cu cât a crescut sau scăzut " +
        "cash-ul în perioadă. Operațional + Investiții + Finanțare.",
  },
  inlineFormula: "CFO + CFI + CFF",
  related: ["operating_cash_flow", "investing_cash_flow", "financing_cash_flow", "closing_cash"],
  computation: (ctx, value) => {
    const m = ctx.metrics ?? {};
    return {
      result: { value, format: "currency" },
      layout: "stacked",
      tokens: [
        { type: "value", value: m.operatingCashFlow ?? 0, conceptKey: "operating_cash_flow", label: "CFO", format: "currency" },
        { type: "operator", op: "+" },
        { type: "value", value: m.investingCashFlow ?? 0, conceptKey: "investing_cash_flow", label: "CFI", format: "currency" },
        { type: "operator", op: "+" },
        { type: "value", value: m.financingCashFlow ?? 0, conceptKey: "financing_cash_flow", label: "CFF", format: "currency" },
      ],
    };
  },
};

const opening_cash: Concept = {
  key: "opening_cash",
  name: { en: "Opening Cash", ro: "Cash la început" },
  category: "Cash Flow",
  shortDefinition: {
    en: "Cash balance at the start of the period. Same as last period's " +
        "closing cash.",
    ro: "Soldul de cash la începutul perioadei. Egal cu soldul de cash de la " +
        "sfârșitul perioadei anterioare.",
  },
  related: ["closing_cash", "net_change_in_cash"],
};

const closing_cash: Concept = {
  key: "closing_cash",
  name: { en: "Closing Cash", ro: "Cash la final" },
  category: "Cash Flow",
  shortDefinition: {
    en: "Cash balance at the end of the period. Should reconcile to the Balance " +
        "Sheet cash position within rounding.",
    ro: "Soldul de cash la sfârșitul perioadei. Trebuie să corespundă cu cash-ul " +
        "din Bilanț, până la rotunjire.",
  },
  related: ["opening_cash", "net_change_in_cash", "cash_ratio"],
  computation: (ctx, value) => {
    const m = ctx.metrics ?? {};
    return {
      result: { value, format: "currency" },
      layout: "stacked",
      tokens: [
        { type: "value", value: m.openingCash ?? 0, conceptKey: "opening_cash", label: "Opening", format: "currency" },
        { type: "operator", op: "+" },
        { type: "value", value: m.netChangeInCash ?? 0, conceptKey: "net_change_in_cash", label: "Net Change", format: "currency" },
      ],
    };
  },
};

// ─── P&L concepts ─────────────────────────────────────────────────────────

const cogs: Concept = {
  key: "cogs",
  name: { en: "Cost of Goods Sold", ro: "Cost al bunurilor vândute" },
  category: "Profitability",
  shortDefinition: {
    en: "Direct cost of producing or buying the goods/services sold — raw " +
        "materials, direct labor, merchandise. Subtracted from revenue to get " +
        "gross profit.",
    ro: "Costul direct al producerii sau cumpărării bunurilor/serviciilor vândute — " +
        "materii prime, manoperă directă, mărfuri. Se scade din venituri pentru " +
        "a obține profitul brut.",
  },
  inlineFormula: "Σ Class 6 direct cost accounts",
  related: ["revenue", "gross_margin", "operating_expenses"],
};

const operating_expenses: Concept = {
  key: "operating_expenses",
  name: { en: "Operating Expenses", ro: "Cheltuieli operaționale" },
  category: "Profitability",
  shortDefinition: {
    en: "Costs of running the business beyond direct goods costs — personnel, " +
        "rent, utilities, marketing, depreciation. Subtracted from gross profit " +
        "to get operating profit.",
    ro: "Costuri de funcționare ale afacerii în afara costurilor directe — " +
        "personal, chirie, utilități, marketing, amortizare. Se scad din profitul " +
        "brut pentru a obține profitul operațional.",
  },
  related: ["cogs", "ebitda", "ebit"],
};

const ebit: Concept = {
  key: "ebit",
  name: { en: "EBIT", ro: "EBIT (rezultat operațional)" },
  category: "Profitability",
  shortDefinition: {
    en: "Earnings before interest and taxes — operating profit including " +
        "depreciation. Used for interest coverage and ROIC calculations.",
    ro: "Profit înainte de dobânzi și impozit — rezultat operațional incluzând " +
        "amortizarea. Folosit pentru acoperirea dobânzilor și ROIC.",
  },
  inlineFormula: "Revenue − COGS − OpEx",
  related: ["ebitda", "depreciation_amortization", "interest_coverage", "net_profit"],
  computation: (ctx, value) => {
    const m = ctx.metrics ?? {};
    return {
      result: { value, format: "currency", conceptKey: "ebit" },
      layout: "stacked",
      tokens: [
        {
          type: "value",
          value: m.revenue ?? 0,
          conceptKey: "revenue",
          label: "Revenue",
          format: "currency",
        },
        { type: "operator", op: "−" },
        {
          type: "value",
          value: m.cogs ?? 0,
          conceptKey: "cogs",
          label: "COGS",
          format: "currency",
        },
        { type: "operator", op: "−" },
        {
          type: "value",
          value: m.opex ?? 0,
          conceptKey: "operating_expenses",
          label: "OpEx",
          format: "currency",
        },
      ],
    };
  },
};

const net_financial_result: Concept = {
  key: "net_financial_result",
  name: { en: "Net Financial Result", ro: "Rezultat financiar net" },
  category: "Profitability",
  shortDefinition: {
    en: "Financial income (interest received, FX gains) minus financial expense " +
        "(interest paid, FX losses). Often negative for a borrowing business.",
    ro: "Venituri financiare (dobânzi încasate, câștiguri de curs) minus " +
        "cheltuieli financiare (dobânzi plătite, pierderi de curs). Adesea " +
        "negativ pentru o afacere îndatorată.",
  },
  related: ["ebit", "net_profit", "interest_coverage"],
};

const income_tax: Concept = {
  key: "income_tax",
  name: { en: "Income Tax", ro: "Impozit pe profit" },
  category: "Profitability",
  shortDefinition: {
    en: "Tax expense on profit before tax. For Romanian companies the standard " +
        "rate is 16% on profit; micro-companies may be on turnover-based regimes.",
    ro: "Cheltuiala fiscală pe profitul înainte de impozit. Cota standard este " +
        "16% pe profit; micro-companiile pot fi pe regimul de cifră de afaceri.",
  },
  related: ["ebit", "net_profit", "net_financial_result"],
};

// ─── Balance Sheet concepts ───────────────────────────────────────────────

const total_assets: Concept = {
  key: "total_assets",
  name: { en: "Total Assets", ro: "Total active" },
  category: "Liquidity",
  shortDefinition: {
    en: "Everything the company owns or controls — cash, receivables, inventory, " +
        "equipment, intangibles. Must equal Total Equity + Liabilities (the BS " +
        "balance check).",
    ro: "Tot ce deține sau controlează compania — cash, creanțe, stocuri, " +
        "echipamente, intangibile. Trebuie să fie egal cu Capital propriu + Datorii.",
  },
  plainEnglish: {
    en: "All the things the business has — money in the bank, customers who " +
        "owe you, stock on the shelves, machines and buildings.",
    ro: "Toate lucrurile pe care le are afacerea — bani în bancă, clienți care " +
        "datorează, stocuri, utilaje, clădiri.",
  },
  related: ["total_equity_liab", "current_assets", "non_current_assets"],
  computation: (ctx, value) => {
    const m = ctx.metrics ?? {};
    return {
      result: { value, format: "currency" },
      layout: "stacked",
      tokens: [
        { type: "value", value: m.nonCurrentAssets ?? 0, conceptKey: "non_current_assets", label: "Non-Current", format: "currency" },
        { type: "operator", op: "+" },
        { type: "value", value: m.currentAssets ?? 0, conceptKey: "current_assets", label: "Current", format: "currency" },
      ],
    };
  },
};

const total_equity_liab: Concept = {
  key: "total_equity_liab",
  name: { en: "Total Equity & Liabilities", ro: "Total capital propriu și datorii" },
  category: "Liquidity",
  shortDefinition: {
    en: "How the assets are funded — shareholder equity plus all debts. Must " +
        "equal Total Assets.",
    ro: "Cum sunt finanțate activele — capitalul acționarilor plus toate datoriile. " +
        "Trebuie să fie egal cu Total Active.",
  },
  related: ["total_assets", "shareholders_equity", "current_liabilities", "long_term_debt"],
};

const current_assets: Concept = {
  key: "current_assets",
  name: { en: "Current Assets", ro: "Active circulante" },
  category: "Liquidity",
  shortDefinition: {
    en: "Assets expected to become cash within 12 months — cash itself, " +
        "receivables, inventory, prepayments. The numerator of the current ratio.",
    ro: "Active care urmează să devină cash în 12 luni — cash, creanțe, stocuri, " +
        "avansuri. Numărătorul indicatorului lichidității curente.",
  },
  plainEnglish: {
    en: "The cash + things that turn into cash this year — bank balance, " +
        "customers' unpaid invoices, stock on the shelves.",
    ro: "Cash-ul plus tot ce devine cash în acest an — soldul din bancă, " +
        "facturile neîncasate, stocurile din depozit.",
  },
  related: ["current_liabilities", "current_ratio", "receivables", "inventory", "closing_cash"],
};

const non_current_assets: Concept = {
  key: "non_current_assets",
  name: { en: "Non-Current Assets", ro: "Active imobilizate" },
  category: "Liquidity",
  shortDefinition: {
    en: "Long-lived assets — property, equipment, intangibles, long-term " +
        "investments. The productive base of the business.",
    ro: "Active pe termen lung — clădiri, echipamente, intangibile, investiții " +
        "pe termen lung. Baza productivă a afacerii.",
  },
  plainEnglish: {
    en: "The big stuff that lasts years — factories, machines, vehicles, " +
        "software licenses, the brand.",
    ro: "Lucrurile mari care țin ani — fabrici, utilaje, mașini, licențe " +
        "software, brandul.",
  },
  related: ["ppe", "capex", "total_assets"],
};

const current_liabilities: Concept = {
  key: "current_liabilities",
  name: { en: "Current Liabilities", ro: "Datorii curente" },
  category: "Liquidity",
  shortDefinition: {
    en: "Debts due within 12 months — trade payables, short-term bank debt, " +
        "tax payable, dividends declared. Denominator of liquidity ratios.",
    ro: "Datorii scadente în 12 luni — datorii comerciale, credite bancare " +
        "pe termen scurt, taxe, dividende declarate. Numitorul indicatorilor de lichiditate.",
  },
  plainEnglish: {
    en: "Bills the business has to pay within a year — suppliers, the bank's " +
        "short-term line, payroll, taxes.",
    ro: "Facturile pe care trebuie să le plătească într-un an — furnizori, " +
        "linia de credit, salarii, impozite.",
  },
  related: ["current_assets", "current_ratio", "cash_ratio", "quick_ratio"],
};

const long_term_debt: Concept = {
  key: "long_term_debt",
  name: { en: "Long-Term Debt", ro: "Datorii pe termen lung" },
  category: "Leverage & Solvency",
  shortDefinition: {
    en: "Borrowings with more than 12 months to maturity — bank loans, " +
        "bonds, leasing. Drives leverage and interest coverage.",
    ro: "Împrumuturi cu scadență peste 12 luni — credite bancare, obligațiuni, " +
        "leasing. Influențează gradul de îndatorare și acoperirea dobânzilor.",
  },
  plainEnglish: {
    en: "Loans the business doesn't have to pay back this year — the multi-year " +
        "term loan, the equipment lease, bonds.",
    ro: "Credite care nu trebuie rambursate anul acesta — creditul pe mai mulți " +
        "ani, leasing-ul de utilaj, obligațiuni.",
  },
  related: ["interest_coverage", "net_debt_ebitda", "lt_debt_drawdowns", "lt_debt_repayments"],
};

const total_debt: Concept = {
  key: "total_debt",
  name: { en: "Total Debt", ro: "Total datorii financiare" },
  category: "Leverage & Solvency",
  shortDefinition: {
    en: "Sum of long-term plus short-term interest-bearing debt. Used to " +
        "compute Net Debt / EBITDA and Debt / Equity.",
    ro: "Suma datoriilor cu dobândă pe termen lung și scurt. Folosită pentru " +
        "calculul Net Debt / EBITDA și Debt / Equity.",
  },
  plainEnglish: {
    en: "All the money the business owes to banks and lenders — short-term " +
        "lines and long-term loans together. This is gross debt, before " +
        "subtracting the cash you have in the bank.",
    ro: "Toți banii datorați băncilor și creditorilor — linii pe termen scurt " +
        "și credite pe termen lung împreună. Aceasta este datoria brută, " +
        "înainte de scăderea cash-ului din bancă.",
  },
  sourceTrace: () => ({
    sourceType: "trial_balance_account",
    accounts: [
      { code: "162", label: "Long-term bank loans", amount: 0, side: "C" },
      { code: "167", label: "Leasing obligations", amount: 0, side: "C" },
      { code: "519", label: "Short-term bank loans / revolvers", amount: 0, side: "C" },
    ],
  }),
  inlineFormula: "LT Debt + ST Debt",
  related: ["long_term_debt", "net_debt_ebitda", "ebitda"],
  computation: (ctx, value) => {
    const m = ctx.metrics ?? {};
    return {
      result: { value, format: "currency" },
      layout: "stacked",
      tokens: [
        { type: "value", value: m.longTermDebt ?? 0, conceptKey: "long_term_debt", label: "LT Debt", format: "currency" },
        { type: "operator", op: "+" },
        { type: "value", value: m.shortTermDebt ?? 0, conceptKey: "short_term_debt", label: "ST Debt", format: "currency" },
      ],
    };
  },
};

const shareholders_equity: Concept = {
  key: "shareholders_equity",
  name: { en: "Shareholders' Equity", ro: "Capital propriu" },
  category: "Leverage & Solvency",
  shortDefinition: {
    en: "What shareholders own after all debts are paid — share capital plus " +
        "retained earnings plus reserves. The 'cushion' of the balance sheet.",
    ro: "Ce dețin acționarii după plata tuturor datoriilor — capital social " +
        "plus profit reportat plus rezerve. „Pernă” a bilanțului.",
  },
  plainEnglish: {
    en: "What the shareholders would walk away with if the business sold " +
        "all its assets today and paid off every creditor. The book value " +
        "floor of the business.",
    ro: "Ce ar primi acționarii dacă firma ar vinde azi tot și ar plăti " +
        "toți creditorii. Pragul valorii contabile al afacerii.",
  },
  sourceTrace: () => ({
    sourceType: "trial_balance_account",
    accounts: [
      { code: "1012", label: "Paid-in share capital", amount: 0, side: "C" },
      { code: "104", label: "Share premium / merger premium", amount: 0, side: "C" },
      { code: "105", label: "Revaluation reserve", amount: 0, side: "C" },
      { code: "106", label: "Legal & other reserves", amount: 0, side: "C" },
      { code: "117", label: "Retained earnings (cumulative)", amount: 0, side: "C" },
      { code: "121", label: "Current-year profit / loss", amount: 0, side: "C" },
    ],
  }),
  related: ["total_assets", "total_equity_liab", "net_profit"],
};

const inventory: Concept = {
  key: "inventory",
  name: { en: "Inventory", ro: "Stocuri" },
  category: "Working Capital",
  shortDefinition: {
    en: "Raw materials, work-in-progress, and finished goods on hand. Cash " +
        "locked in stock until it sells.",
    ro: "Materii prime, producție în curs și produse finite în stoc. Cash " +
        "blocat în stoc până când se vinde.",
  },
  plainEnglish: {
    en: "Stuff sitting on shelves — raw materials waiting to be used, finished " +
        "products waiting to be sold. Cash you can't spend yet.",
    ro: "Lucruri pe raft — materii prime de folosit, produse finite de vândut. " +
        "Cash blocat până se vând.",
  },
  related: ["dio_days", "current_assets", "working_capital_changes"],
};

const receivables: Concept = {
  key: "receivables",
  name: { en: "Trade Receivables", ro: "Creanțe comerciale" },
  category: "Working Capital",
  shortDefinition: {
    en: "Money customers owe but haven't yet paid. Higher receivables vs sales " +
        "mean customers pay slowly — cash is trapped.",
    ro: "Bani datorați de clienți dar neîncasați încă. Creanțe mari raportate la " +
        "vânzări înseamnă încasări lente — cash blocat.",
  },
  plainEnglish: {
    en: "Invoices you've sent but customers haven't paid yet. Counts as an " +
        "asset because they will pay — eventually.",
    ro: "Facturile emise dar pe care clienții încă nu le-au plătit. Sunt activ " +
        "pentru că vor plăti — cândva.",
  },
  related: ["dso_days", "current_assets", "working_capital_changes"],
};

const ppe: Concept = {
  key: "ppe",
  name: { en: "Property, Plant & Equipment", ro: "Imobilizări corporale" },
  category: "Liquidity",
  shortDefinition: {
    en: "Land, buildings, machinery, vehicles, fixtures — the physical assets " +
        "used in the business. Shown net of accumulated depreciation.",
    ro: "Terenuri, clădiri, utilaje, vehicule, mobilier — activele fizice folosite " +
        "în afacere. Prezentate net de amortizarea cumulată.",
  },
  plainEnglish: {
    en: "The physical stuff the business owns — land, buildings, machines, " +
        "vehicles. Loses value over time (depreciation).",
    ro: "Lucrurile fizice deținute — terenuri, clădiri, utilaje, vehicule. " +
        "Își pierd valoarea în timp (amortizare).",
  },
  related: ["capex", "depreciation_amortization", "non_current_assets"],
};

const operating_revenue: Concept = {
  key: "operating_revenue",
  name: { en: "Operating Revenue", ro: "Venituri operaționale" },
  category: "Profitability",
  shortDefinition: {
    en: "Total revenue from the company's main operating activities. The " +
        "denominator for every margin ratio.",
    ro: "Total venituri din activitatea principală a companiei. Numitorul " +
        "pentru toate marjele.",
  },
  related: ["revenue", "ebitda_margin", "gross_margin"],
};

const gross_profit: Concept = {
  key: "gross_profit",
  name: { en: "Gross Profit", ro: "Profit brut" },
  category: "Profitability",
  shortDefinition: {
    en: "Revenue minus cost of goods sold — the margin left after paying for " +
        "what was sold, before operating expenses.",
    ro: "Venituri minus costul bunurilor vândute — marja rămasă după plata " +
        "costului direct, înainte de cheltuielile operaționale.",
  },
  inlineFormula: "Revenue − COGS",
  related: ["operating_revenue", "cogs", "gross_margin", "ebit"],
};

const interest_expense: Concept = {
  key: "interest_expense",
  name: { en: "Interest Expense", ro: "Cheltuieli cu dobânzile" },
  category: "Profitability",
  shortDefinition: {
    en: "Interest paid on bank loans, bonds, and leasing. Drives the interest " +
        "coverage ratio and is subtracted from EBIT to reach pretax profit.",
    ro: "Dobânzi plătite la credite bancare, obligațiuni și leasing. Influențează " +
        "indicatorul de acoperire a dobânzii și se scade din EBIT pentru profitul brut.",
  },
  inlineFormula: "Σ Account 666",
  related: ["ebit", "interest_coverage", "long_term_debt", "net_financial_result"],
};

const pretax_profit: Concept = {
  key: "pretax_profit",
  name: { en: "Profit Before Tax", ro: "Profit înainte de impozit" },
  category: "Profitability",
  shortDefinition: {
    en: "Profit after operating result and financial result, before income tax. " +
        "The base for computing the effective tax rate.",
    ro: "Profitul după rezultatul operațional și financiar, înainte de impozit. " +
        "Baza pentru calculul cotei efective de impozit.",
  },
  inlineFormula: "EBIT + Net Financial Result",
  related: ["ebit", "net_financial_result", "income_tax", "net_profit"],
};

// ─── Balance Sheet — additional concepts referenced by bucket mapping ─────

const cash: Concept = {
  key: "cash",
  name: { en: "Cash & Cash Equivalents", ro: "Disponibilități bănești" },
  category: "Liquidity",
  shortDefinition: {
    en: "Money in bank accounts and on hand. The most liquid asset; closing " +
        "cash here must reconcile to the Cash Flow Statement.",
    ro: "Bani din conturi bancare și casierie. Activul cel mai lichid; soldul " +
        "de aici trebuie să corespundă cu cel din Cash Flow.",
  },
  plainEnglish: {
    en: "Money in the bank, right now. The number you can actually spend " +
        "tomorrow without selling anything or borrowing.",
    ro: "Banii din bancă, acum. Suma pe care o poți cheltui mâine fără să " +
        "vinzi ceva sau să te împrumuți.",
  },
  related: ["closing_cash", "cash_ratio", "current_assets"],
  sourceTrace: () => ({
    sourceType: "trial_balance_account",
    accounts: [
      { code: "5121", label: "Bank accounts in RON", amount: 0, side: "D" },
      { code: "5124", label: "Bank accounts in FX", amount: 0, side: "D" },
      { code: "5125", label: "Cash in transit / other bank", amount: 0, side: "D" },
      { code: "531", label: "Petty cash", amount: 0, side: "D" },
    ],
  }),
};

const accounts_payable: Concept = {
  key: "accounts_payable",
  name: { en: "Trade Payables", ro: "Datorii comerciale" },
  category: "Working Capital",
  shortDefinition: {
    en: "What the company owes suppliers for goods/services already received. " +
        "Higher payables relative to purchases means slower payment — a free " +
        "source of working-capital financing.",
    ro: "Ce datorează compania furnizorilor pentru bunuri/servicii deja primite. " +
        "Datorii mari raportate la achiziții = plata mai lentă a furnizorilor — " +
        "sursă gratuită de finanțare a capitalului de lucru.",
  },
  plainEnglish: {
    en: "Supplier bills the business has received but not paid yet. Free " +
        "short-term funding — until the supplier loses patience.",
    ro: "Facturi de la furnizori primite dar neplătite încă. Finanțare gratuită " +
        "pe termen scurt — până când furnizorul își pierde răbdarea.",
  },
  related: ["dpo_days", "working_capital_changes", "current_liabilities"],
};

const short_term_debt: Concept = {
  key: "short_term_debt",
  name: { en: "Short-Term Debt", ro: "Datorii pe termen scurt" },
  category: "Leverage & Solvency",
  shortDefinition: {
    en: "Interest-bearing debt due within 12 months — bank overdrafts, revolvers, " +
        "current portion of long-term loans. Together with LT debt, makes total debt.",
    ro: "Datorii cu dobândă scadente în 12 luni — descoperit de cont, linii de " +
        "credit, partea curentă a creditelor pe termen lung. Împreună cu datoriile " +
        "pe termen lung formează datoria totală.",
  },
  related: ["long_term_debt", "total_debt", "current_liabilities"],
};

const share_capital: Concept = {
  key: "share_capital",
  name: { en: "Share Capital", ro: "Capital social" },
  category: "Leverage & Solvency",
  shortDefinition: {
    en: "Paid-in capital — what shareholders originally contributed. Separate " +
        "from retained earnings and reserves accumulated since.",
    ro: "Capital vărsat — ce au contribuit acționarii inițial. Separat de profitul " +
        "reportat și rezervele acumulate ulterior.",
  },
  inlineFormula: "Σ Account 1012",
  related: ["shareholders_equity", "retained_earnings"],
};

const retained_earnings: Concept = {
  key: "retained_earnings",
  name: { en: "Retained Earnings", ro: "Profit reportat" },
  category: "Leverage & Solvency",
  shortDefinition: {
    en: "Cumulative net profit kept in the business since inception, after " +
        "dividends paid. Reflects the historical earnings power retained.",
    ro: "Profitul net cumulat reținut în afacere de la înființare, după dividende " +
        "plătite. Reflectă puterea istorică de a genera profit, păstrată în firmă.",
  },
  inlineFormula: "Σ Account 117 (closing balance)",
  related: ["shareholders_equity", "net_profit", "dividends_paid"],
};

/** Statement-views concept pack. Merged into the master registry by
 *  concepts/index.ts alongside SEED_CONCEPTS. */
export const STATEMENT_CONCEPTS: Readonly<Record<string, Concept>> = {
  // Cash Flow
  [net_profit.key]: net_profit,
  [depreciation_amortization.key]: depreciation_amortization,
  [operating_cash_flow_before_wc.key]: operating_cash_flow_before_wc,
  [working_capital_changes.key]: working_capital_changes,
  [operating_cash_flow.key]: operating_cash_flow,
  [capex.key]: capex,
  [investing_cash_flow.key]: investing_cash_flow,
  [lt_debt_drawdowns.key]: lt_debt_drawdowns,
  [lt_debt_repayments.key]: lt_debt_repayments,
  [dividends_paid.key]: dividends_paid,
  [financing_cash_flow.key]: financing_cash_flow,
  [net_change_in_cash.key]: net_change_in_cash,
  [opening_cash.key]: opening_cash,
  [closing_cash.key]: closing_cash,
  // P&L
  [operating_revenue.key]: operating_revenue,
  [cogs.key]: cogs,
  [gross_profit.key]: gross_profit,
  [operating_expenses.key]: operating_expenses,
  [ebit.key]: ebit,
  [net_financial_result.key]: net_financial_result,
  [interest_expense.key]: interest_expense,
  [pretax_profit.key]: pretax_profit,
  [income_tax.key]: income_tax,
  // BS
  [total_assets.key]: total_assets,
  [total_equity_liab.key]: total_equity_liab,
  [current_assets.key]: current_assets,
  [non_current_assets.key]: non_current_assets,
  [current_liabilities.key]: current_liabilities,
  [long_term_debt.key]: long_term_debt,
  [short_term_debt.key]: short_term_debt,
  [total_debt.key]: total_debt,
  [shareholders_equity.key]: shareholders_equity,
  [share_capital.key]: share_capital,
  [retained_earnings.key]: retained_earnings,
  [inventory.key]: inventory,
  [receivables.key]: receivables,
  [accounts_payable.key]: accounts_payable,
  [cash.key]: cash,
  [ppe.key]: ppe,
};
