"""K8 — THE ENGINE BOOK docs gate.

The engine book (docs/engine_book/**) is GENERATED, never hand-rotted:
`scripts/generate_engine_book.py` derives the architecture diagrams from
the real import graph, the invariant catalog from the family markers in
the src/test trees, the ADR index from docs/decisions/, and the money
path from the modules that actually carry the cent. K8 proves, in the
standard battery:

  1. Regeneration is BYTE-IDENTICAL to the committed book (the same
     discipline as the pack-port --check gates) — run via the script's
     own --check subprocess, the exact invocation CI uses.
  2. Every catalogued invariant resolves to at least one COLLECTED test
     (pytest --collect-only cross-reference; the battery itself proves
     those tests pass). An uncovered invariant must be a frozen entry in
     the generator's known-gaps register — and a STALE register entry
     (gap since covered) fails generation too, so the register only
     shrinks consciously.
  3. The committed ADR index matches the actual contents of
     docs/decisions/.
  4. Every always-on assert id in src/engine is catalogued in
     docs/engine_book/assertions.md (read-only cross-check of the
     assertions agent's page — never edited here).

Wording note: this docstring deliberately avoids bare marker mentions of
other invariant families, because the generator discovers family ids by
scanning tests/engine — naming them here would list this file as an
"enforcing test" for invariants it does not enforce. K8 itself is the
one id this file legitimately claims.
"""

from __future__ import annotations

import importlib.util
import subprocess
import sys
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[2]
GENERATOR = REPO / "scripts" / "generate_engine_book.py"
BOOK_DIR = REPO / "docs" / "engine_book"
DECISIONS_DIR = REPO / "docs" / "decisions"


def _load_generator():
    spec = importlib.util.spec_from_file_location("generate_engine_book", GENERATOR)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)  # type: ignore[union-attr]
    return mod


@pytest.fixture(scope="module")
def book():
    return _load_generator()


@pytest.fixture(scope="module")
def catalog(book):
    """The invariant catalog. Building it already enforces the
    generation-time half of the gate: an id with no resolving test that
    is not a frozen known-gaps entry raises, as does a stale entry."""
    return book.build_catalog()


# ── 1. Byte-identical regeneration (the committed book == the tree) ────

def test_regeneration_is_byte_identical():
    proc = subprocess.run(
        [sys.executable, str(GENERATOR), "--check"],
        cwd=str(REPO),
        capture_output=True,
        text=True,
    )
    assert proc.returncode == 0, (
        "engine book drift — the committed docs/engine_book pages no longer "
        "match regeneration from the tree. Run "
        "`python scripts/generate_engine_book.py` and commit.\n"
        "stdout:\n%s\nstderr:\n%s" % (proc.stdout, proc.stderr)
    )


def test_owned_pages_exist_and_carry_generated_header(book):
    for name in book.OWNED_PAGES:
        page = BOOK_DIR / name
        assert page.exists(), "generated book page missing: %s" % name
        assert page.read_text(encoding="utf-8").startswith(
            "<!-- GENERATED by scripts/generate_engine_book.py"
        ), "%s lost its generated header" % name


def test_generator_never_writes_agent_owned_pages(book):
    assert set(book.FOREIGN_PAGES) == {
        "assertions.md", "mutation.md", "ai_payload_audit.md", "error_budget.md",
        # Hand-maintained: the TC-### testing rules. Listed here so adding
        # a hand-maintained page stays a deliberate two-file act — the
        # generator must never overwrite one.
        "testing_conventions.md",
        # Hand-maintained: the gate register. Its content is a record of
        # gates OBSERVED going red, which no generator can derive from
        # the tree; tests/engine/test_gate_canaries.py enforces that
        # every battery gate has an entry.
        "gates.md",
    }
    pages = book.generate()
    for foreign in book.FOREIGN_PAGES:
        assert foreign not in pages


# ── 2. Every catalogued invariant resolves to a collected test ─────────

def test_every_invariant_resolves_to_a_collected_test(book, catalog):
    assert catalog, "empty invariant catalog — discovery is broken"

    covered = {k: v for k, v in catalog.items() if v["tests"]}
    gaps = {k for k, v in catalog.items() if not v["tests"]}
    assert gaps == set(book.KNOWN_GAPS), (
        "known-gaps register out of sync with the catalog: %r" % gaps
    )

    all_files = sorted({f for v in covered.values() for f in v["tests"]})
    proc = subprocess.run(
        # -o addopts= neutralizes the repo's "-v" addopts so -q yields the
        # short "file::test" listing this parses.
        [sys.executable, "-m", "pytest", "--collect-only", "-q",
         "-o", "addopts=", "-p", "no:cacheprovider"]
        + all_files,
        cwd=str(REPO),
        capture_output=True,
        text=True,
    )
    assert proc.returncode == 0, (
        "collect-only failed on the catalog's enforcing test files:\n%s\n%s"
        % (proc.stdout[-4000:], proc.stderr[-4000:])
    )

    # Files that actually yielded collected test items.
    collected_files = set()
    for line in proc.stdout.splitlines():
        if "::" in line:
            collected_files.add(line.split("::", 1)[0].strip())

    failures = []
    for inv_id, entry in sorted(covered.items()):
        if not any(f in collected_files for f in entry["tests"]):
            failures.append("%s -> %s" % (inv_id, entry["tests"]))
    assert not failures, (
        "catalogued invariants whose enforcing files yield NO collected "
        "tests:\n  " + "\n  ".join(failures)
    )


def test_this_gate_is_itself_catalogued(catalog):
    entry = catalog.get("K8")
    assert entry is not None, "the docs gate lost its own catalog entry"
    assert "tests/engine/test_engine_book.py" in entry["tests"]


# ── 3. ADR index matches docs/decisions/ ───────────────────────────────

def test_adr_index_matches_decisions_dir(book):
    committed = (BOOK_DIR / "adr_index.md").read_text(encoding="utf-8")
    assert committed == book.render_adr_index(), (
        "adr_index.md does not match docs/decisions/ — regenerate the book"
    )
    for f in sorted(DECISIONS_DIR.glob("*.md")):
        assert ("(../decisions/%s)" % f.name) in committed, (
            "ADR missing from the committed index: %s" % f.name
        )


# ── 4. Assert ids in src are all catalogued in assertions.md ───────────

def test_every_src_assert_id_is_in_assertions_page(book):
    assertions_page = (BOOK_DIR / "assertions.md").read_text(encoding="utf-8")
    missing = [
        aid for aid in sorted(book.discover_assert_ids())
        if aid not in assertions_page
    ]
    assert not missing, (
        "assert ids present in src/engine but absent from "
        "docs/engine_book/assertions.md: %s" % ", ".join(missing)
    )
