#!/usr/bin/env python3
"""THE ENGINE BOOK generator — docs/engine_book/** derived from the tree at HEAD.

GENERATED, NEVER HAND-ROTTED. Every page this script owns is derived from
the actual repository state:

  architecture.md   C4-style views (context / container / component) whose
                    container+component diagrams are rendered from the REAL
                    import graph of src/engine (ast-parsed, relative imports
                    resolved) — a diagram that no longer matches the code
                    cannot regenerate byte-identical, so the K8 gate fails.
  invariants.md     THE INVARIANT CATALOG — every family (closing-identity /
                    gateway, property, architecture, metamorphic, advisory,
                    crash/proof, assert ids, diagnosis + reconcile codes)
                    discovered by scanning the src and test trees for the
                    family markers, each id linked to its enforcing tests.
                    An id with NO resolving test is a catalog gap: it must
                    appear in KNOWN_GAPS (visible, frozen, driven to zero)
                    or generation FAILS.
  adr_index.md      Index of docs/decisions/ (title = first heading).
  money_path.md     One page tracing a cent from spreadsheet cell to served
                    statement; module paths and assert ids are read from the
                    tree (missing module or moved assert = generation fails).
  threat_model.md   STRIDE-lite, one page. The prose is fixed here (written
                    once), but every mitigation's gate path is verified to
                    exist at generation time.
  INDEX.md          The book's table of contents (links the agent-owned
                    assertions.md / mutation.md / ai_payload_audit.md
                    without touching them).

NOT owned (never written here): assertions.md, mutation.md, ai_payload_audit.md, error_budget.md.

Usage:
  python scripts/generate_engine_book.py           # (re)write the book
  python scripts/generate_engine_book.py --check   # regenerate in memory and
                                                   # byte-diff against the
                                                   # committed book (the same
                                                   # discipline as
                                                   # port_ro_pack.py --check)

Exit codes: 0 = written (or --check clean); 1 = --check drift or a
generation-time integrity failure (missing module, uncovered invariant
outside KNOWN_GAPS, ...).

Gate: tests/engine/test_engine_book.py (K8) runs --check plus the
collected-test cross-reference in the standard battery.
"""

from __future__ import annotations

import argparse
import ast
import re
import sys
from pathlib import Path
from typing import Dict, List, Optional, Set, Tuple

REPO = Path(__file__).resolve().parents[1]
SRC_ENGINE = REPO / "src" / "engine"
TESTS_ENGINE = REPO / "tests" / "engine"
BOOK_DIR = REPO / "docs" / "engine_book"
DECISIONS_DIR = REPO / "docs" / "decisions"
PYPROJECT = REPO / "pyproject.toml"

GENERATED_HEADER = (
    "<!-- GENERATED by scripts/generate_engine_book.py — do not hand-edit.\n"
    "     Regenerate with: python scripts/generate_engine_book.py\n"
    "     Drift gate: tests/engine/test_engine_book.py (K8) -->\n"
)

#: Pages this generator owns. assertions.md / mutation.md / ai_payload_audit.md are owned by
#: other agents and are only LINKED from INDEX.md, never written.
OWNED_PAGES = (
    "INDEX.md",
    "architecture.md",
    "invariants.md",
    "adr_index.md",
    "money_path.md",
    "threat_model.md",
)
FOREIGN_PAGES = (
    "assertions.md", "mutation.md", "ai_payload_audit.md", "error_budget.md"
)


class BookError(RuntimeError):
    """Generation-time integrity failure (drift between book model and tree)."""


# ──────────────────────────────────────────────────────────────────────
# Import-graph extraction (architecture.md)
# ──────────────────────────────────────────────────────────────────────

def _iter_engine_modules() -> List[Path]:
    return sorted(p for p in SRC_ENGINE.rglob("*.py"))


def _module_name(path: Path) -> str:
    """src/engine/api/_reconcile.py -> engine.api._reconcile;
    src/engine/ir/__init__.py -> engine.ir."""
    rel = path.relative_to(SRC_ENGINE.parent)
    parts = list(rel.with_suffix("").parts)
    if parts[-1] == "__init__":
        parts = parts[:-1]
    return ".".join(parts)


def _module_exists(dotted: str) -> bool:
    rel = Path(*dotted.split(".")[1:]) if dotted.startswith("engine") else None
    if dotted == "engine":
        return True
    if rel is None:
        return False
    return (SRC_ENGINE / rel).with_suffix(".py").exists() or (
        SRC_ENGINE / rel / "__init__.py"
    ).exists()


def _imports_of(path: Path) -> Tuple[Set[str], Set[str]]:
    """Return (engine_targets, external_toplevel_names) for one module."""
    tree = ast.parse(path.read_text(encoding="utf-8"))
    mod = _module_name(path)
    parts = mod.split(".")
    is_pkg = path.name == "__init__.py"
    engine_targets: Set[str] = set()
    external: Set[str] = set()

    def _add_engine(target: str, names: Optional[List[str]] = None) -> None:
        if not (target == "engine" or target.startswith("engine.")):
            return
        engine_targets.add(target)
        for n in names or []:
            cand = target + "." + n
            if _module_exists(cand):
                engine_targets.add(cand)

    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                if alias.name == "engine" or alias.name.startswith("engine."):
                    _add_engine(alias.name)
                else:
                    external.add(alias.name.split(".")[0])
        elif isinstance(node, ast.ImportFrom):
            if node.level:
                base = parts if is_pkg else parts[:-1]
                strip = node.level - 1
                if strip:
                    base = base[: len(base) - strip]
                target = ".".join(base + (node.module.split(".") if node.module else []))
                _add_engine(target, [a.name for a in node.names])
            else:
                target = node.module or ""
                if target == "engine" or target.startswith("engine."):
                    _add_engine(target, [a.name for a in node.names])
                elif target:
                    external.add(target.split(".")[0])
    engine_targets.discard(mod)
    return engine_targets, external


def _package_of(dotted: str) -> str:
    """Grouping unit for the container view: first component under engine,
    if it is a real sub-package; root modules group as '(root)'."""
    parts = dotted.split(".")
    if len(parts) < 2:
        return "(root)"
    if (SRC_ENGINE / parts[1]).is_dir():
        return parts[1]
    return "(root)"


def build_import_graph() -> Dict[str, object]:
    modules = _iter_engine_modules()
    per_module: Dict[str, Set[str]] = {}
    per_module_external: Dict[str, Set[str]] = {}
    for p in modules:
        mod = _module_name(p)
        eng, ext = _imports_of(p)
        per_module[mod] = eng
        per_module_external[mod] = ext

    pkg_modules: Dict[str, Set[str]] = {}
    for mod in per_module:
        pkg_modules.setdefault(_package_of(mod), set()).add(mod)

    # Container edges: (importer_pkg, imported_pkg) -> number of importing modules
    edges: Dict[Tuple[str, str], Set[str]] = {}
    for mod, targets in per_module.items():
        src_pkg = _package_of(mod)
        for t in targets:
            dst_pkg = _package_of(t)
            if dst_pkg != src_pkg:
                edges.setdefault((src_pkg, dst_pkg), set()).add(mod)

    return {
        "per_module": per_module,
        "per_module_external": per_module_external,
        "pkg_modules": pkg_modules,
        "pkg_edges": {k: len(v) for k, v in edges.items()},
    }


def _declared_third_party() -> Dict[str, str]:
    """Import-name -> declared-dist-name map derived from pyproject.toml
    [project].dependencies (plus the import-name aliases)."""
    text = PYPROJECT.read_text(encoding="utf-8")
    m = re.search(r"^dependencies\s*=\s*\[(.*?)^\]", text, re.M | re.S)
    if not m:
        raise BookError("pyproject.toml: could not locate [project] dependencies")
    dists = re.findall(r'"([A-Za-z0-9_.-]+?)\s*[><=!~\[]', m.group(1))
    aliases = {"pyyaml": "yaml", "pymupdf": "fitz", "python-dateutil": "dateutil"}
    out: Dict[str, str] = {}
    for dist in dists:
        out[aliases.get(dist.lower(), dist.lower().replace("-", "_"))] = dist
    return out


# ──────────────────────────────────────────────────────────────────────
# Invariant discovery (invariants.md)
# ──────────────────────────────────────────────────────────────────────

#: Bare single-letter family markers scanned in tests/engine.  D and R are
#: deliberately EXCLUDED here: bare "R1"/"R2" also name the advisory-pass
#: hard rules, so the diagnosis/reconcile code families resolve by their
#: FULL code strings instead (see below).
_LETTER_MARKER = re.compile(r"\b([IKMNPV])(\d{1,2})\b")
#: A-### assert ids; the lookbehind keeps "SHA-256" from minting "A-256".
_ASSERT_ID = re.compile(r"(?<![A-Za-z0-9-])A-(\d{3})(?!\d)")
#: Full diagnosis / reconcile code strings, as emitted by the engine.
_DIAG_CODE = re.compile(r'"((?:D\d|R\d|R)_[A-Z][A-Z_]+)"')

FAMILIES = {
    "I": "Closing-identity / facts-gateway serving contract",
    "P": "Property suite (hypothesis, real production chain)",
    "N": "Architecture invariants (IR, packs, boundaries, N7 gate)",
    "M": "Metamorphic suite (algebraic relations, no oracles)",
    "V": "AI advisory pass (additive, never blocking)",
    "K": "Crash-safety / journal / proof gates",
    "A": "Assertion-dense kernel (Tiger-style always-on asserts)",
    "D": "Deterministic BS diagnosis codes",
    "R": "Reconciliation proposal codes",
}

#: Curated one-line meanings.  An id discovered in the tree but missing
#: here renders a loud placeholder — and since the committed book must be
#: byte-identical to regeneration, the placeholder forces the author who
#: introduced the id to describe it (or consciously commit the placeholder).
CURATED_MEANING = {
    "I2": "BALANCED serving: gateway totals == canonical totals exactly, in integer cents; raw == adjusted on every concept.",
    "I3": "RECONCILED serving: gateway == the ADJUSTED figures while every raw_*() accessor still returns the unchanged source cents.",
    "I4": "Status contract: present_status never yields a 'balanced'-family display for machine RECONCILED; the API serialization uses its output verbatim.",
    "P1": "Source cents never mutate through the pipeline.",
    "P2": "Adjustments are strictly additive.",
    "P3": "Conservation, including unclassified value (AI-lane half under P8).",
    "P4": "Auto-reconcile triggers iff 0 < ratio <= 0.001.",
    "P5": "RECONCILED is never serialized as BALANCED, on any surface.",
    "P6": "Idempotence: pipeline(pipeline(x)) == pipeline(x).",
    "P7": "Permutation invariance of source rows.",
    "P8": "AI-lane labels + needs_review array survive the serve path.",
    "P9": "Model quarantine: deterministic diagnoses never construct an AI client.",
    "N1": "Front-end round-trip byte-stability + content_hash stability for every corpus input.",
    "N2": "Front-end -> IR mapping fidelity (keystone suite + explicit coverage-closure census).",
    "N3": "Pack pinning + effective-dated resolution (a 2024 period keeps its 2024 pack).",
    "N5": "ABSENT is not ZERO, end to end through the Phase-1 IR.",
    "N6": "Currency scales HUF(0) / RON(2) / KWD(3) flow through Money and the IR.",
    "N7": "New-jurisdiction acceptance gate: a jurisdiction lands tree-only (packs + fixtures), never by editing engine code.",
    "M1": "Scale x10^k: every statement figure scales exactly; the reconcile-gate ratio is scale-invariant (exact Fraction).",
    "M2": "Merge: two BALANCED docs concatenated stay BALANCED; totals and section subtotals additive to the cent.",
    "M3": "Mirror: swapping debit/credit columns flips the sign of difference exactly (scoped side-exchange in M3b).",
    "M4": "Scale-neutrality: same minor units at different Money scales produce byte-identical statements.",
    "M5": "Label immutability: scrambled account labels change no number in the assembled envelope.",
    "M6": "Row order: any permutation yields a byte-identical canonical_bs and assembled envelope.",
    "V1": "Status invariance: machine status with the advisory pass ON == OFF; served payload byte-identical.",
    "V2": "Byte-invariance: gateway facts identical ON/OFF.",
    "V3": "Failure isolation: model timeout / API error / credits-out -> ai_review absent + degraded flag, all else byte-identical.",
    "V4": "needs_review escalation accepts atom/account IDs only; a value raises TypeError by signature.",
    "V5": "Findings cannot flip status; forged keys are stripped by the whitelist projection.",
    "V6": "Reconcile quarantine: the reconcile flow never constructs the ai_validator client.",
    "V7": "ai_review survives the serve stage intact and never leaks INTO the served payload.",
    "K1": "Typed hash-chained journal events + tamper detection.",
    "K2": "Idempotent resume: a run interrupted at any stage boundary resumes to a byte-identical result.",
    "K3": "Duplicate delivery short-circuits to the existing chain.",
    "K4": "Encryption seam DO-NOT-FLIP: provider_from_env returns the passthrough even with ENGINE_ENCRYPTION_KEY set — turning encryption on is a deliberate future wave.",
    "K5": "Encryption-seam boundary honesty: a frame-magic blob is refused by the passthrough and the keyed stub refuses to fabricate ciphertext.",
    "K8": "The engine-book docs gate: regeneration is byte-identical and every catalogued invariant resolves to a collected test.",
    "K9": "As-of time travel: scan -> undo -> re-scan, then as-of each era.",
    "D0_ANCHOR_DIVERGENCE": "Extracted column sums diverge from the file's own totals row.",
    "D1_SOURCE_IMBALANCED": "The FILE's own column pair D != C — the source is honestly imbalanced.",
    "D2_FINGERPRINT": "Layout fingerprint mismatch on a known exporter format.",
    "D3_CONTRA_MISPLACED": "A contra account sits on the wrong statement side.",
    "D4_BIFUNCTIONAL_SIDE": "A bifunctional account was placed by the wrong closing side.",
    "D5_DUPLICATE_ROWS": "Duplicate account rows detected in the source.",
    "D7_MAGNITUDE": "A magnitude anomaly (scale slip) in extracted values.",
    "D8_OMITTED": "A value-bearing account was omitted from the statement (builder census).",
    "D9_UNMAPPED_INCLUDED": "An unmapped account's value is included and flagged, never silently dropped (builder-emitted).",
    "R1_ROUNDING_CENTS": "Auto-fix proposal: sub-threshold rounding drift in cents.",
    "R2_SINGLE_UNMAPPED_MATCH": "Auto-fix proposal: exactly one unmapped account equals the delta to the cent.",
    "R3_SIDE_FLIP": "Proposal: a half-match account balances the statement when its side is flipped.",
    "R4_AI_PROPOSAL": "AI-lane reconcile proposal (never auto-applied; deterministic validator stays the gate).",
    "R_DUP_TOTALS_ROW": "Proposal: a duplicated totals row explains the delta.",
}

#: Catalogued invariants with NO resolving test — visible, frozen, and to be
#: driven to zero.  A NEW uncovered id fails generation; covering one of
#: these without removing it here fails the K8 gate (stale-allowlist check).
KNOWN_GAPS = {
    "R3_SIDE_FLIP": (
        "The side-flip PROPOSAL path in engine/api/_reconcile.py is not yet "
        "exercised by a test naming its code (side-flip mechanics themselves "
        "are covered via classify/shadow suites, e.g. side_flipped assertions "
        "in test_shadow_divergence.py)."
    ),
}


def _test_files() -> List[Path]:
    return sorted(p for p in TESTS_ENGINE.rglob("test_*.py"))


def _rel(p: Path) -> str:
    return p.relative_to(REPO).as_posix()


def discover_letter_invariants() -> Dict[str, List[str]]:
    """Bare-marker families in tests/engine: id -> sorted test files."""
    found: Dict[str, Set[str]] = {}
    for tf in _test_files():
        text = tf.read_text(encoding="utf-8")
        for m in _LETTER_MARKER.finditer(text):
            found.setdefault(m.group(0), set()).add(_rel(tf))
    return {k: sorted(v) for k, v in found.items()}


def discover_assert_ids() -> Dict[str, Dict[str, List[str]]]:
    """A-### ids: anchors in src/engine + witness test files in tests/engine."""
    src_anchor: Dict[str, Set[str]] = {}
    for p in _iter_engine_modules():
        text = p.read_text(encoding="utf-8")
        for m in _ASSERT_ID.finditer(text):
            src_anchor.setdefault(m.group(0), set()).add(_rel(p))
    witnesses: Dict[str, Set[str]] = {}
    for tf in _test_files():
        text = tf.read_text(encoding="utf-8")
        for m in _ASSERT_ID.finditer(text):
            if m.group(0) in src_anchor:
                witnesses.setdefault(m.group(0), set()).add(_rel(tf))
    return {
        aid: {"src": sorted(mods), "tests": sorted(witnesses.get(aid, set()))}
        for aid, mods in sorted(src_anchor.items())
    }


def discover_diag_codes() -> Dict[str, Dict[str, List[str]]]:
    """Full D*/R* code strings: defining src modules + resolving test files."""
    defined: Dict[str, Set[str]] = {}
    for p in _iter_engine_modules():
        text = p.read_text(encoding="utf-8")
        for m in _DIAG_CODE.finditer(text):
            defined.setdefault(m.group(1), set()).add(_rel(p))
    resolved: Dict[str, Set[str]] = {}
    for tf in _test_files():
        text = tf.read_text(encoding="utf-8")
        for code in defined:
            if code in text:
                resolved.setdefault(code, set()).add(_rel(tf))
    return {
        code: {"src": sorted(mods), "tests": sorted(resolved.get(code, set()))}
        for code, mods in sorted(defined.items())
    }


def build_catalog() -> Dict[str, Dict[str, object]]:
    """The full invariant catalog: id -> {family, meaning, tests, src}.

    Raises BookError when an id has no resolving test and is not a frozen
    KNOWN_GAPS entry — that is the generation-time half of K8's teeth.
    """
    catalog: Dict[str, Dict[str, object]] = {}

    for inv_id, files in discover_letter_invariants().items():
        catalog[inv_id] = {
            "family": inv_id[0],
            "meaning": CURATED_MEANING.get(
                inv_id,
                "(uncatalogued — add a curated meaning in scripts/generate_engine_book.py)",
            ),
            "tests": files,
            "src": [],
        }

    for aid, info in discover_assert_ids().items():
        catalog[aid] = {
            "family": "A",
            "meaning": "Always-on kernel assert — full contract + witness in assertions.md.",
            "tests": info["tests"],
            "src": info["src"],
        }

    for code, info in discover_diag_codes().items():
        catalog[code] = {
            "family": "D" if code.startswith("D") else "R",
            "meaning": CURATED_MEANING.get(
                code,
                "(uncatalogued — add a curated meaning in scripts/generate_engine_book.py)",
            ),
            "tests": info["tests"],
            "src": info["src"],
        }

    uncovered = sorted(k for k, v in catalog.items() if not v["tests"])
    unexpected = [k for k in uncovered if k not in KNOWN_GAPS]
    if unexpected:
        raise BookError(
            "invariants with NO resolving test (add a test or, consciously, "
            "a KNOWN_GAPS entry): %s" % ", ".join(unexpected)
        )
    stale = sorted(k for k in KNOWN_GAPS if k not in uncovered)
    if stale:
        raise BookError(
            "stale KNOWN_GAPS entries (now covered or no longer defined — "
            "remove them): %s" % ", ".join(stale)
        )
    return catalog


# ──────────────────────────────────────────────────────────────────────
# Money path model (money_path.md) — verified against the tree
# ──────────────────────────────────────────────────────────────────────

MONEY_PATH_STEPS = [
    {
        "title": "Front-end parse — the cell becomes an atom with a source_ref",
        "modules": ["src/engine/frontends", "src/engine/ir/schema.py"],
        "invariants": ["N1", "N2", "M5"],
        "prose": (
            "A registered front-end (saga6/saga10/generic4/csv/positional-pdf/"
            "llm-extractor via `frontends/registry.py`) reads the uploaded file and "
            "emits IR atoms; every amount carries a `source_ref` (sheet/row/col "
            "provenance, serialized in `ir/schema.py`) so the cent stays traceable "
            "to its exact cell."
        ),
    },
    {
        "title": "IR Money — exact integer minor units, one unit per algebra",
        "modules": ["src/engine/ir/money.py", "src/engine/ir/ledgerdoc.py"],
        "invariants": ["N5", "N6"],
        "prose": (
            "The amount is frozen as `Money` (exact int minor units — floats "
            "never enter the algebra) inside an immutable `LedgerDoc`; ABSENT "
            "and ZERO stay distinct."
        ),
    },
    {
        "title": "Classify — the atom gets a rule id from the jurisdiction pack",
        "modules": ["src/engine/passes/classify.py", "src/engine/packs"],
        "invariants": ["N3", "N7"],
        "prose": (
            "`passes/classify.py` assigns each atom a statement line via the "
            "pinned, effective-dated rules pack (classified-or-unclassified, "
            "never guessed, never dropped)."
        ),
    },
    {
        "title": "Canonical builder — partitioned into the closing identity",
        "modules": ["src/engine/country_packs/ro_romania/canonical_adapter.py"],
        "invariants": ["I2", "P1", "P3", "D8_OMITTED", "D9_UNMAPPED_INCLUDED"],
        "prose": (
            "The pack's canonical adapter partitions every signed closing "
            "balance onto exactly one statement side; row/total partition "
            "asserts hold to the cent and unmapped value is included + flagged, "
            "never dropped."
        ),
    },
    {
        "title": "Auto-reconcile gate — diagnose, propose, adjust additively",
        "modules": [
            "src/engine/api/_reconcile.py",
            "src/engine/confidence/reconciliation_checks.py",
        ],
        "invariants": ["P2", "P4", "P5", "P9", "M1"],
        "prose": (
            "A non-balanced envelope gets a deterministic diagnosis (D-codes) "
            "and reversible proposals (R-codes); sub-threshold drift is "
            "auto-fixed at persist, always additively — source cents are never "
            "rewritten and RECONCILED is never dressed up as BALANCED."
        ),
    },
    {
        "title": "Facts gateway — the ONE typed reader of served truth",
        "modules": ["src/engine/serving/facts.py", "src/engine/serving/status.py"],
        "invariants": ["I2", "I3", "I4"],
        "prose": (
            "`FactsGateway` serves adjusted figures while raw accessors keep "
            "the untouched source cents; `present_status` owns every status "
            "display. `scripts/check_import_boundary.py` keeps all other code "
            "out of the raw snapshot."
        ),
    },
    {
        "title": "Surfaces — pipeline persist/serve, journaled",
        "modules": ["src/engine/api/pipeline.py", "src/engine/journal"],
        "invariants": ["K1", "K2", "P6", "P8", "V1"],
        "prose": (
            "`api/pipeline.py` persists the envelope (additive-only contract) and "
            "the journal hash-chains every stage boundary, so the served cent "
            "is replayable, resumable and as-of addressable."
        ),
    },
]


def _assert_ids_in(module_path: str) -> List[str]:
    """A-ids actually present under a repo-relative module path (file or dir)."""
    root = REPO / module_path
    if not root.exists():
        raise BookError("money_path step names a missing module: %s" % module_path)
    files = [root] if root.is_file() else sorted(root.rglob("*.py"))
    ids: Set[str] = set()
    for f in files:
        for m in _ASSERT_ID.finditer(f.read_text(encoding="utf-8")):
            ids.add(m.group(0))
    return sorted(ids)


# ──────────────────────────────────────────────────────────────────────
# Rendering
# ──────────────────────────────────────────────────────────────────────

def _mermaid_id(name: str) -> str:
    return re.sub(r"[^A-Za-z0-9_]", "_", name)


def render_architecture(graph: Dict[str, object]) -> str:
    pkg_modules: Dict[str, Set[str]] = graph["pkg_modules"]  # type: ignore[assignment]
    pkg_edges: Dict[Tuple[str, str], int] = graph["pkg_edges"]  # type: ignore[assignment]
    per_module: Dict[str, Set[str]] = graph["per_module"]  # type: ignore[assignment]
    per_module_external: Dict[str, Set[str]] = graph["per_module_external"]  # type: ignore[assignment]

    lines: List[str] = [GENERATED_HEADER]
    lines.append("# Engine architecture (C4-style, derived from the import graph)\n")
    lines.append(
        "All package and module edges below are read from the actual `import`\n"
        "statements in `src/engine` (ast-parsed, relative imports resolved).\n"
        "If the code moves, this page regenerates differently and the K8 gate\n"
        "fails until the committed book is regenerated.\n"
    )

    # Level 1 — context (static by nature: the systems around the engine).
    lines.append("## Level 1 — system context\n")
    lines.append("```mermaid")
    lines.append("graph LR")
    lines.append('    user(["Operator / SME user"])')
    lines.append('    fe["Frontend (Vite SPA)"]')
    lines.append('    engine["Python engine (src/engine)"]')
    lines.append('    supabase[("Supabase (Postgres + storage + edge fns)")]')
    lines.append('    anthropic["Anthropic API (advisory + AI lane)"]')
    lines.append('    stripe["Stripe (billing)"]')
    lines.append("    user --> fe")
    lines.append("    fe -->|/api| engine")
    lines.append("    engine --> supabase")
    lines.append("    engine -->|breaker-capped| anthropic")
    lines.append("    engine --> stripe")
    lines.append("```\n")

    # Level 2 — container view: packages of src/engine + real edges.
    lines.append("## Level 2 — containers: packages of `src/engine`\n")
    lines.append(
        "Edge label = number of distinct modules in the source package that\n"
        "import the target package.\n"
    )
    lines.append("```mermaid")
    lines.append("graph LR")
    for pkg in sorted(pkg_modules):
        label = "%s (%d modules)" % (pkg, len(pkg_modules[pkg]))
        lines.append('    %s["%s"]' % (_mermaid_id("pkg_" + pkg), label))
    for (a, b), n in sorted(pkg_edges.items()):
        lines.append(
            "    %s -->|%d| %s"
            % (_mermaid_id("pkg_" + a), n, _mermaid_id("pkg_" + b))
        )
    lines.append("```\n")

    # Level 3 — component view: module-level graph over the value path.
    scope_pkgs = ["ai", "canonical", "frontends", "ir", "journal", "passes", "serving"]
    scope_mods = ["engine.api.pipeline", "engine.api._reconcile"]
    scope: Set[str] = set(scope_mods)
    for pkg in scope_pkgs:
        scope |= pkg_modules.get(pkg, set())
    missing = [m for m in scope if m not in per_module]
    if missing:
        raise BookError("component-view scope names missing modules: %s" % missing)
    lines.append("## Level 3 — components: the value path, module level\n")
    lines.append(
        "Scope: `%s` packages plus `engine.api.pipeline` (the document\n"
        "pipeline — `engine.pipeline` is the legacy SKU engine) and\n"
        "`engine.api._reconcile`; edges are real imports inside that scope.\n"
        % "`, `".join(scope_pkgs)
    )
    lines.append("```mermaid")
    lines.append("graph LR")
    by_pkg: Dict[str, List[str]] = {}
    for mod in sorted(scope):
        by_pkg.setdefault(_package_of(mod), []).append(mod)
    for pkg in sorted(by_pkg):
        lines.append('    subgraph %s["%s"]' % (_mermaid_id("sg_" + pkg), pkg))
        for mod in by_pkg[pkg]:
            short = mod.split(".")[-1] if mod.count(".") else mod
            lines.append('        %s["%s"]' % (_mermaid_id(mod), short))
        lines.append("    end")
    for mod in sorted(scope):
        for t in sorted(per_module[mod]):
            if t in scope:
                lines.append("    %s --> %s" % (_mermaid_id(mod), _mermaid_id(t)))
    lines.append("```\n")

    # Declared third-party usage per package (supply-chain view).
    tp = _declared_third_party()
    lines.append("## Declared third-party imports per package\n")
    lines.append(
        "Import sites of dependencies declared in `pyproject.toml` (the\n"
        "2026-08-22 httpx incident class: an import here without a matching\n"
        "declaration is the supply-chain lock's job to reject).\n"
    )
    lines.append("| package | third-party imports (declared dist) |")
    lines.append("|---|---|")
    pkg_tp: Dict[str, Set[str]] = {}
    for mod, ext in per_module_external.items():
        hits = {"%s (%s)" % (name, tp[name]) for name in ext if name in tp}
        if hits:
            pkg_tp.setdefault(_package_of(mod), set()).update(hits)
    for pkg in sorted(pkg_tp):
        lines.append("| `%s` | %s |" % (pkg, ", ".join(sorted(pkg_tp[pkg]))))
    lines.append("")
    return "\n".join(lines)


def render_invariants(catalog: Dict[str, Dict[str, object]]) -> str:
    lines: List[str] = [GENERATED_HEADER]
    lines.append("# The invariant catalog\n")
    lines.append(
        "Every invariant family enforced on the engine, discovered from the\n"
        "tree (family markers in `tests/engine`, assert ids and diagnosis\n"
        "codes in `src/engine`) and linked to its enforcing tests. An\n"
        "invariant with no resolving test fails generation unless it is a\n"
        "frozen, visible entry in the known-gaps register below — that is\n"
        "the K8 gate's teeth (`tests/engine/test_engine_book.py`).\n"
        "\n"
        "The *enforced by* column lists every test file carrying the id's\n"
        "marker — the defining suite plus any suite that cross-references\n"
        "it (bare single-letter markers are file-level attributions).\n"
    )

    def _sort_key(inv_id: str) -> Tuple[str, int, str]:
        m = re.match(r"^([A-Z])-?(\d+)", inv_id)
        if m:
            return (m.group(1), int(m.group(2)), inv_id)
        return (inv_id[0], 999, inv_id)

    order = ["I", "P", "N", "M", "V", "K", "A", "D", "R"]
    for fam in order:
        ids = sorted((k for k, v in catalog.items() if v["family"] == fam), key=_sort_key)
        if not ids:
            continue
        lines.append("## %s-family — %s\n" % (fam, FAMILIES[fam]))
        if fam == "A":
            lines.append(
                "Per-assert contracts and witness anchors live in\n"
                "[assertions.md](assertions.md) (owned by the assertions agent).\n"
            )
        lines.append("| invariant | meaning | defined in | enforced by |")
        lines.append("|---|---|---|---|")
        for inv_id in ids:
            entry = catalog[inv_id]
            src = ", ".join("`%s`" % s for s in entry["src"]) or "—"
            tests = (
                ", ".join("`%s`" % t for t in entry["tests"])
                or "**NONE — known gap (see register below)**"
            )
            lines.append("| `%s` | %s | %s | %s |" % (inv_id, entry["meaning"], src, tests))
        lines.append("")

    lines.append("## Known-gaps register (drive to zero)\n")
    if KNOWN_GAPS:
        lines.append("| invariant | why it is still uncovered |")
        lines.append("|---|---|")
        for code in sorted(KNOWN_GAPS):
            lines.append("| `%s` | %s |" % (code, KNOWN_GAPS[code]))
    else:
        lines.append("(none — every catalogued invariant resolves to a test)")
    lines.append("")
    return "\n".join(lines)


def render_adr_index() -> str:
    lines: List[str] = [GENERATED_HEADER]
    lines.append("# ADR index — `docs/decisions/`\n")
    files = sorted(DECISIONS_DIR.glob("*.md"))
    if not files:
        raise BookError("docs/decisions/ has no ADRs — refusing to render an empty index")
    lines.append("| ADR | title |")
    lines.append("|---|---|")
    for f in files:
        title = ""
        for line in f.read_text(encoding="utf-8").splitlines():
            if line.startswith("#"):
                title = line.lstrip("#").strip()
                break
        lines.append("| [`%s`](../decisions/%s) | %s |" % (f.name, f.name, title or "(untitled)"))
    lines.append("")
    return "\n".join(lines)


def render_money_path(catalog: Dict[str, Dict[str, object]]) -> str:
    lines: List[str] = [GENERATED_HEADER]
    lines.append("# The money path — one cent, cell to statement\n")
    lines.append(
        "Each step names the module that carries the cent and the invariant\n"
        "ids guarding it (each id resolves in [invariants.md](invariants.md);\n"
        "assert ids are re-read from the named modules at generation time, so\n"
        "a moved assert or module fails the K8 gate).\n"
    )
    lines.append("```mermaid")
    lines.append("graph TD")
    prev = None
    for i, step in enumerate(MONEY_PATH_STEPS, 1):
        node = "s%d" % i
        lines.append('    %s["%d. %s"]' % (node, i, step["title"].split(" — ")[0]))
        if prev:
            lines.append("    %s --> %s" % (prev, node))
        prev = node
    lines.append("```\n")
    for i, step in enumerate(MONEY_PATH_STEPS, 1):
        lines.append("## %d. %s\n" % (i, step["title"]))
        lines.append(step["prose"] + "\n")
        lines.append("| module | always-on asserts found here |")
        lines.append("|---|---|")
        for mod in step["modules"]:
            aids = _assert_ids_in(mod)
            lines.append("| `%s` | %s |" % (mod, ", ".join("`%s`" % a for a in aids) or "—"))
        for inv in step["invariants"]:
            if inv not in catalog:
                raise BookError(
                    "money_path step %d names invariant %r not in the catalog" % (i, inv)
                )
        lines.append("")
        lines.append(
            "Guarding invariants: %s\n" % ", ".join("`%s`" % v for v in step["invariants"])
        )
    return "\n".join(lines)


#: Threat-model mitigations: (gate label, repo-relative path that must exist).
THREAT_GATES = [
    ("import boundary checker", "scripts/check_import_boundary.py"),
    ("corpus byte-replay", "scripts/corpus_replay.py"),
    ("determinism gate", "scripts/verify_determinism.py"),
    ("corpus redaction policy", "scripts/check_corpus_policy.py"),
    ("scrub tooling unreachable", "scripts/check_scrub_tooling_unreachable.py"),
    ("AI spend breaker", "src/engine/ai/breaker.py"),
    ("model registry (roles, not raw keys)", "src/engine/ai/models.yaml"),
    ("journal hash chain + verify CLI", "scripts/journal_cli.py"),
    ("pack lint", "scripts/pack_lint.py"),
    ("BS drift measure", "scripts/measure_bs_drift.py"),
    ("anthropic egress probe", "scripts/check_anthropic_probe.py"),
]


def render_threat_model() -> str:
    for label, path in THREAT_GATES:
        if not (REPO / path).exists():
            raise BookError("threat model names a missing gate: %s (%s)" % (label, path))
    g = {path.split("/")[-1]: "`%s`" % path for _, path in THREAT_GATES}
    lines: List[str] = [GENERATED_HEADER]
    lines.append("# Threat model (STRIDE-lite, one page)\n")
    lines.append(
        "The prose is written once; every gate path referenced below is\n"
        "verified to exist at generation time, so a renamed or deleted gate\n"
        "fails the K8 gate.\n"
    )
    lines.append("## Assets\n")
    lines.append(
        "1. **Source documents** — uploaded trial balances / PDFs; customer\n"
        "   financial data, redacted before any corpus use.\n"
        "2. **Envelopes** — the served financial truth (canonical_bs and the\n"
        "   assembled statements); integrity is the product.\n"
        "3. **The journal** — hash-chained event history; the audit trail.\n"
        "4. **AI keys and spend** — Anthropic/OpenAI credentials and budget.\n"
    )
    lines.append("## Trust boundaries and mitigations\n")
    lines.append("| boundary | threat (STRIDE) | mitigation — the enforcing gate |")
    lines.append("|---|---|---|")
    lines.append(
        "| **Upload** (user file -> engine) | Tampering / DoS: malformed or "
        "adversarial files driving wrong numbers | Typed front-end parsing into "
        "the exact-int IR with always-on asserts; deterministic diagnosis "
        "(D-codes) instead of silent repair; corpus replay %s and determinism "
        "%s pin behavior byte-for-byte |" % (g["corpus_replay.py"], g["verify_determinism.py"])
    )
    lines.append(
        "| **AI egress** (engine -> model APIs) | Info disclosure: customer "
        "data leaving; spend abuse; a model mutating truth | Advisory pass is "
        "additive-and-never-blocking (V-family); deterministic lanes never "
        "construct a client; per-role daily caps in the breaker %s; roles "
        "resolved via the registry %s; egress probed by %s |"
        % (g["breaker.py"], g["models.yaml"], g["check_anthropic_probe.py"])
    )
    lines.append(
        "| **Serve** (engine -> FE/API) | Tampering / elevation: bypassing the "
        "gateway to read raw snapshots or re-dress statuses | The facts gateway "
        "is the one typed reader (I-family); %s rejects out-of-boundary imports; "
        "additive-only envelope guard; status semantics locked |"
        % g["check_import_boundary.py"]
    )
    lines.append(
        "| **Git / corpus** (what gets committed) | Info disclosure: "
        "unredacted customer data in history; repudiation of results | Corpus "
        "policy gate %s; scrub tooling kept unreachable from runtime %s; "
        "journal hash chain + verify %s makes served history tamper-evident; "
        "pack changes linted %s and drift-measured %s |"
        % (
            g["check_corpus_policy.py"],
            g["check_scrub_tooling_unreachable.py"],
            g["journal_cli.py"],
            g["pack_lint.py"],
            g["measure_bs_drift.py"],
        )
    )
    lines.append("")
    lines.append(
        "Out of scope here: Supabase RLS and billing hardening (tracked in\n"
        "`CLAUDE.md` §16 and the security-hardening migration), and the\n"
        "dependency lock/SBOM (Part E owns making the 2026-08-22 httpx\n"
        "incident class impossible).\n"
    )
    return "\n".join(lines)


def render_index() -> str:
    lines: List[str] = [GENERATED_HEADER]
    lines.append("# THE ENGINE BOOK\n")
    lines.append(
        "Living documentation, drift-checked: the pages marked *generated*\n"
        "are produced by `scripts/generate_engine_book.py` from the tree at\n"
        "HEAD, and `tests/engine/test_engine_book.py` (the K8 docs gate)\n"
        "fails whenever regeneration is not byte-identical to what is\n"
        "committed — the book cannot rot silently.\n"
    )
    lines.append("| page | what it is | maintained by |")
    lines.append("|---|---|---|")
    lines.append(
        "| [architecture.md](architecture.md) | C4-style views derived from the real import graph of `src/engine` | generated |"
    )
    lines.append(
        "| [invariants.md](invariants.md) | The invariant catalog — every family, each id linked to its enforcing tests | generated |"
    )
    lines.append(
        "| [money_path.md](money_path.md) | One cent traced from spreadsheet cell to served statement, with the guarding invariants | generated |"
    )
    lines.append(
        "| [threat_model.md](threat_model.md) | STRIDE-lite threat model; gate paths verified at generation time | generated |"
    )
    lines.append(
        "| [adr_index.md](adr_index.md) | Index of `docs/decisions/` | generated |"
    )
    lines.append(
        "| [assertions.md](assertions.md) | A-### assert catalog with witness tests | assertions agent (hand-maintained) |"
    )
    lines.append(
        "| [mutation.md](mutation.md) | Mutation-testing results and policy | mutation agent (hand-maintained) |"
    )
    lines.append(
        "| [ai_payload_audit.md](ai_payload_audit.md) | What each AI call site sends off-box, with over-sharing flags | supply-chain agent (hand-maintained) |"
    )
    lines.append(
        "| [error_budget.md](error_budget.md) | Silent-error-rate definition, budgets (DO NOT WIDEN), measurement protocol incl. the weekly production-sampling operator procedure, and the latest measured numbers | error-budget agent (hand-maintained) |"
    )
    lines.append(
        "| [../ADDING_A_JURISDICTION.md](../ADDING_A_JURISDICTION.md) | The pack-authoring runbook (tree-only jurisdiction adds) | hand-maintained runbook |"
    )
    lines.append("")
    lines.append("## Regenerating\n")
    lines.append("```")
    lines.append("python scripts/generate_engine_book.py          # rewrite the generated pages")
    lines.append("python scripts/generate_engine_book.py --check  # CI/battery drift check")
    lines.append("```")
    lines.append("")
    return "\n".join(lines)


# ──────────────────────────────────────────────────────────────────────
# Entry point
# ──────────────────────────────────────────────────────────────────────

def generate() -> Dict[str, str]:
    """Render every owned page. Returns {relative filename: content}."""
    graph = build_import_graph()
    catalog = build_catalog()
    return {
        "INDEX.md": render_index(),
        "architecture.md": render_architecture(graph),
        "invariants.md": render_invariants(catalog),
        "adr_index.md": render_adr_index(),
        "money_path.md": render_money_path(catalog),
        "threat_model.md": render_threat_model(),
    }


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="regenerate in memory and byte-diff against the committed book",
    )
    args = parser.parse_args(argv)

    try:
        pages = generate()
    except BookError as exc:
        print("ENGINE BOOK GENERATION FAILED: %s" % exc, file=sys.stderr)
        return 1

    assert set(pages) == set(OWNED_PAGES)
    for foreign in FOREIGN_PAGES:
        assert foreign not in pages, "refusing to write agent-owned page %s" % foreign

    if args.check:
        drift: List[str] = []
        for name, content in sorted(pages.items()):
            target = BOOK_DIR / name
            if not target.exists():
                drift.append("%s: MISSING (never generated?)" % name)
            elif target.read_text(encoding="utf-8") != content:
                drift.append("%s: DRIFT (committed page != regeneration)" % name)
        if drift:
            print("ENGINE BOOK DRIFT — regenerate and commit:", file=sys.stderr)
            for d in drift:
                print("  " + d, file=sys.stderr)
            print("  fix: python scripts/generate_engine_book.py", file=sys.stderr)
            return 1
        print("engine book: clean (%d generated pages byte-identical)" % len(pages))
        return 0

    BOOK_DIR.mkdir(parents=True, exist_ok=True)
    for name, content in sorted(pages.items()):
        (BOOK_DIR / name).write_text(content, encoding="utf-8")
        print("wrote docs/engine_book/%s" % name)
    return 0


if __name__ == "__main__":
    sys.exit(main())
