// INVENTORY DAYS IN THE DOCUMENTS — the CFO report (screen and PDF: the PDF
// is this HTML posted to the renderer), its workbook, and the forecast
// cockpit's bank export (owner spec 2026-09-26 P1, design B4: "the report
// PDF and the cockpit bank export — all read the block").
//
// Laws, on the committed corpus books (tests/engine/fixtures/firm, the
// served shape) and the engine's own bank-export bytes
// (tests/engine/fixtures/forecast/cockpit_*_export.json, regenerated by
// scripts/gen_cockpit_fixtures.py and held to the route by
// tests/engine/test_forecast_cockpit.py):
//   1. the report prints the ONE block's split — every leg with its
//      accounts and its days, alte stocuri, the basis — as printed by
//      `printInventoryDays`;
//   2. THE TWO DOCUMENTS A BANK READS CARRY ONE SPLIT: the report and the
//      bank export print the identical block, byte for byte, for the same
//      period (the engine's export document carries the period's block);
//   3. the bank export prints the reader's language, the report English;
//   4. the workbook's Ratios sheet carries the same lines;
//   5. a refused block prints the engine's reasons, never a figure; a
//      period with no block prints no section;
//   6. ONE QUANTIZATION IN THE BANK DOCUMENT: the DIO lever row (its value
//      cell and its sentence) prints the split's period-end figure with the
//      characters the split prints — agras printed "31,9" in the lever row
//      and "32 de zile" in the split of the same document.

import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";
import * as XLSX from "xlsx";

import i18n from "@/i18n";
import { buildExcelWorkbook } from "@/lib/financialExports";
import { buildBankExportHtml } from "@/lib/forecastBankExport";
import {
  inventoryDaysDocHtml,
  inventoryDaysSheetRows,
  printDaysQ,
  printInventoryDays,
  readInventoryDaysSplit,
} from "@/lib/inventoryDays";

import { BOOKS, exportHtml, metricsFor, statementsFor } from "./exportBooks";

const REPO = resolve(__dirname, "../../..");
const exportFixture = (book: string): Record<string, unknown> =>
  JSON.parse(readFileSync(resolve(REPO, `tests/engine/fixtures/forecast/cockpit_${book}_export.json`), "utf-8"));

const bank = (book: string, lang: "ro" | "en"): string =>
  buildBankExportHtml({
    payload: exportFixture(book),
    companyName: book,
    lang,
    locale: lang === "ro" ? "ro-RO" : "en-GB",
    t: i18n.getFixedT(lang),
    format: (v: number) => v.toFixed(0),
  });

/** The one inventory-days block a document prints, or null. */
const blockIn = (html: string): string | null => {
  const at = html.indexOf('<div class="inventory-days-split"');
  if (at < 0) return null;
  const end = html.indexOf("</div>", at);
  return html.slice(at, end + "</div>".length);
};

describe("the CFO report prints the ONE served split", () => {
  it.each(BOOKS)("%s: the report carries the block as printInventoryDays prints it", (book) => {
    const s = statementsFor(book);
    const split = readInventoryDaysSplit(s);
    expect(split, `${book} serves no inventory-days block`).not.toBeNull();
    const html = exportHtml(book, s);
    const expected = inventoryDaysDocHtml(printInventoryDays(split!, "en"));
    expect(blockIn(html)).toBe(expected);
    // every leg's figure is the block's value_q (or its engine reason)
    const block = s.inventory_days as { groups: { key: string; value_q: string | null; reason: { text_en: string } | null }[] };
    for (const g of block.groups) {
      const printed = g.value_q ?? g.reason!.text_en;
      expect(expected).toContain(printed);
    }
  });

  it("the developer's refused block prints the engine's reasons and no leg figure", () => {
    const s = statementsFor("realestate");
    const p = printInventoryDays(readInventoryDaysSplit(s)!, "en");
    expect(p.total.refused).toBe(true);
    for (const leg of p.legs) expect(leg.refused).toBe(true);
    expect(blockIn(exportHtml("realestate", s))).toContain('data-refused="1"');
  });

  it("no block, no section", () => {
    const s = statementsFor("agras");
    delete (s as { inventory_days?: unknown }).inventory_days;
    expect(blockIn(exportHtml("agras", s))).toBeNull();
  });
});

describe("the bank export and the CFO report carry one split", () => {
  it.each(["agras", "realestate"])("%s: the engine's export document carries the period's block", (book) => {
    const doc = exportFixture(book).document as { inventory_days: unknown };
    expect(doc.inventory_days).toEqual(statementsFor(book as "agras").inventory_days);
  });

  it.each(["agras", "realestate"])("%s: the bank export (EN) prints the report's block byte for byte", (book) => {
    const reportBlock = blockIn(exportHtml(book as "agras"));
    expect(reportBlock).not.toBeNull();
    expect(blockIn(bank(book, "en"))).toBe(reportBlock);
  });

  it("the bank export prints the reader's language (RO)", () => {
    const html = bank("agras", "ro");
    const s = statementsFor("agras");
    const ro = inventoryDaysDocHtml(printInventoryDays(readInventoryDaysSplit(s)!, "ro"));
    expect(blockIn(html)).toBe(ro);
    expect(ro).toContain("Zile de stoc — pe tipuri de stoc");
    expect(ro).toContain("inclus în total, fără zile proprii");
  });

  it.each(["en", "ro"] as const)(
    "agras: the bank export's DIO lever prints the split's period-end figure, character for character (%s)",
    (lang) => {
      const html = bank("agras", lang);
      const split = readInventoryDaysSplit(statementsFor("agras"))!;
      const q = split.totalClosingQ!;
      expect(q).toBeTruthy();
      const digits = lang === "ro" ? q.replace(".", ",") : q;
      const doc = new DOMParser().parseFromString(html, "text/html");
      const leverLabel = i18n.getFixedT(lang)("forecast.lever.dio_cogs_days");
      const cells = Array.from(doc.querySelectorAll("tr"))
        .map((tr) => Array.from(tr.querySelectorAll("td")).map((td) => (td.textContent ?? "").trim()))
        .find((tds) => tds[0]?.startsWith(lang === "ro" ? "Zile de stoc (DIO)" : "Inventory days (DIO)"));
      expect(cells, `${lang}: no DIO lever row in the bank export (label ${leverLabel})`).toBeTruthy();
      expect(cells![1], `${lang}: the DIO lever row prints ${cells![1]}; the split prints ${digits}`).toBe(digits);
      expect(cells![3].startsWith(`${digits} `), `${lang}: the lever sentence opens "${cells![3].slice(0, 12)}"`).toBe(true);
      // …and the split in the SAME document prints that figure.
      expect(blockIn(html)).toContain(printDaysQ(q, lang));
    },
  );

  it("an export without the block prints no section", () => {
    const payload = exportFixture("agras");
    (payload.document as Record<string, unknown>).inventory_days = null;
    const html = buildBankExportHtml({
      payload, companyName: "agras", lang: "en", locale: "en-GB", t: i18n.getFixedT("en"), format: (v) => v.toFixed(0),
    });
    expect(blockIn(html)).toBeNull();
  });
});

describe("the workbook carries the same lines", () => {
  it("the Ratios sheet ends with the split, the same printed rows", () => {
    const s = statementsFor("agras");
    const wb = buildExcelWorkbook(s, undefined, { metricsByName: metricsFor("agras") } as never);
    const rows = XLSX.utils.sheet_to_json<string[]>(wb.Sheets.Ratios, { header: 1, defval: "" }) as string[][];
    const want = inventoryDaysSheetRows(printInventoryDays(readInventoryDaysSplit(s)!, "en"));
    const at = rows.findIndex((r) => r[0] === want[0][0]);
    expect(at, "the split's title row").toBeGreaterThan(0);
    const got = rows.slice(at, at + want.length).map((r) => r.slice(0, want[1].length).map(String));
    expect(got.map((r, i) => r.slice(0, want[i].length))).toEqual(want);
  });

  // "ON AVERAGE" ONLY ON AN AVERAGE. Every stored period serves the
  // single-day snapshot until it is reprocessed; the DIO card's reading was
  // hard-coded "Stock is held N days on average …" and the workbook printed
  // it beside a formula ending "— stock at 31 December — a single day".
  it("a snapshot period's DIO row never reads 'on average'; an average period's does", () => {
    const dioRow = (s: Record<string, unknown>): string[] => {
      const wb = buildExcelWorkbook(s as never, undefined, { metricsByName: metricsFor("agras") } as never);
      const rows = XLSX.utils.sheet_to_json<string[]>(wb.Sheets.Ratios, { header: 1, defval: "" }) as string[][];
      const row = rows.find((r) => r[1] === "Inventory days (DIO)");
      expect(row, "no DIO row on the Ratios sheet").toBeTruthy();
      return row!.map(String);
    };
    const avg = dioRow(statementsFor("agras") as unknown as Record<string, unknown>);
    expect(avg.join(" | ")).toMatch(/on average/);
    const snap = JSON.parse(JSON.stringify(statementsFor("agras"))) as Record<string, Record<string, unknown>>;
    const blk = snap.inventory_days as Record<string, unknown> & {
      total: Record<string, unknown>; ccc_dio_term: { basis_label: { en: string; ro: string } };
    };
    blk.basis = "year_end_snapshot";
    blk.basis_label = blk.ccc_dio_term.basis_label;
    blk.total.value = blk.total.closing_value;
    blk.total.value_q = blk.total.closing_value_q;
    const row = dioRow(snap).join(" | ");
    expect(row, `the snapshot's DIO row reads an average: ${row}`).not.toMatch(/on average|average of/i);
    expect(row).toContain(blk.ccc_dio_term.basis_label.en);
  });
});
