// reportFooter — the last lines of the report say only what is true for
// THIS report.
//
// Until 2026-10-01 every report ended with three hard-coded sentences:
//
//   "Generated by CFO AI · deterministic engine + Claude Opus 4.7 narrative.
//    Numbers reconcile to the source trial balance within 0.5%. Benchmarks
//    carry source + confidence labels — see Section 5."
//
// Each was false for some report. One calibration book is served with a
// MATERIAL_IMBALANCE and reads 0.9975% on the old drift measure, so "within
// 0.5%" was untrue on the page that printed it; Section 5 is Ratios; and
// the model was credited whether or not a briefing existed. The same words
// would have appeared verbatim in the public sample report.
//
// The footer is now built from the served document:
//   · the balance verdict is the ONE presenter's (servedFacts.presentStatus
//     — the engine-stamped `status_presentation` when served, its mirror
//     otherwise), the same words the BS chip, the HTML export and the Excel
//     status cell print;
//   · the difference is the served `canonical_bs.difference`, to the cent,
//     or the statement that none was served — never a typed tolerance;
//   · the narrative is credited only when a briefing is shown.
//
// Law: lib/__tests__/reportFooter.test.ts (gate public-claims).

import {
  canonicalStatusCore, factsFrom, presentStatus, toDisplay, type BsStatusPresentation,
} from "./servedFacts";
import { moneyLocaleFor } from "./money";
import type { CanonicalBs, Statements } from "./financialReport";

export interface ReportFooterInput {
  /** `GET /api/period` → `statements` (carries `canonical_bs` on every
   *  period the engine verified). */
  statements: unknown;
  currency: string;
  /** True when a briefing body is SHOWN on this report. */
  briefingShown: boolean;
  /** UI language — the figure's number format follows it (CLAUDE.md §26). */
  language: string;
}

export interface ReportFooterLines {
  /** Who computed what. */
  generated: string;
  /** The engine's balance verdict for this report. */
  balance: string;
  /** The difference to the cent, or that none was served. */
  differenceLine: string;
  /** Machine status — for the test id, never printed. */
  machineStatus: string;
}

/** "−12,253.38 RON" / "−12.253,38 RON": the figure in the reader's number
 *  format, the ISO code after it. */
function amountWithCode(n: number, currency: string, language: string): string {
  const fmt = new Intl.NumberFormat(moneyLocaleFor(language), {
    minimumFractionDigits: 2, maximumFractionDigits: 2,
  });
  // Intl prints "-0.00" for a negative zero; a zero difference has no sign.
  const value = Object.is(n, -0) || Math.abs(n) < 0.005 ? 0 : n;
  return `${fmt.format(value)}\u00a0${currency}`;
}

type Rec = Record<string, unknown>;
const isRec = (v: unknown): v is Rec => typeof v === "object" && v !== null && !Array.isArray(v);

/** The verdict and the difference, read ONLY from the served canonical
 *  balance sheet. A period that carries none has no engine verdict — the
 *  footer says that; it never falls back to totals the page added up. */
function servedBalance(
  statements: unknown, currency: string,
): { p: BsStatusPresentation; diff: number | null } {
  const cbs = isRec(statements) && isRec(statements.canonical_bs) ? statements.canonical_bs : null;
  if (!cbs) return { p: presentStatus({ status: null, currency }), diff: null };
  if (isRec(cbs.totals)) {
    const facts = factsFrom({ canonical_bs: cbs } as unknown as Statements);
    return { p: facts.presentStatus(currency), diff: facts.difference() };
  }
  // A served object without its totals block: the verdict and the drift
  // still come through the gateway's own picks (lib/servedFacts) — this
  // module never reads a canonical_bs field itself.
  const core = canonicalStatusCore(cbs as unknown as CanonicalBs);
  const diff = core.differenceCents === null ? null : toDisplay(core.differenceCents);
  return {
    p: presentStatus({
      status: core.status, needsReview: core.needsReview, difference: diff, currency,
    }),
    diff,
  };
}

export function reportFooterLines(input: ReportFooterInput): ReportFooterLines {
  const { p, diff } = servedBalance(input.statements, input.currency);

  const generated =
    "Generated by CFO AI. Every figure is computed by the deterministic engine " +
    "from the uploaded trial balance." +
    (input.briefingShown
      ? " The briefing in section 1 was written by an AI model from these figures."
      : "");

  const differenceLine =
    p.machineStatus === "UNVERIFIED"
      ? "No engine balance verdict exists for this period."
      : diff === null
        ? "Difference: not stated — the served statement carried neither a balance " +
          "difference nor the totals to work one out."
        : `Assets − (Equity + Liabilities) = ${amountWithCode(diff, input.currency, input.language)} on this report.`;

  return {
    generated,
    balance: p.exportHeadline,
    differenceLine,
    machineStatus: p.machineStatus,
  };
}
