// reportFooter — the last lines of the report say only what is true for
// THIS report.
//
// Until 2026-10-01 every report ended with three hard-coded sentences:
//
//   "Generated by CFO AI · deterministic engine + Claude Opus 4.7 narrative.
//    Numbers reconcile to the source trial balance within 0.5%. Benchmarks
//    carry source + confidence labels — see Section 5."
//
// Each was false for some report. One calibration book is served with a
// MATERIAL_IMBALANCE and reads 0.9975% on the old drift measure, so "within
// 0.5%" was untrue on the page that printed it; Section 5 is Ratios; and
// the model was credited whether or not a briefing existed. The same words
// would have appeared verbatim in the public sample report.
//
// The footer is now built from the served document:
//   · the balance verdict is the ONE presenter's (servedFacts.presentStatus
//     — the engine-stamped `status_presentation` when served, its mirror
//     otherwise), the same words the BS chip, the HTML export and the Excel
//     status cell print;
//   · the difference is the served `canonical_bs.difference`, to the cent,
//     or the statement that none was served — never a typed tolerance;
//   · the narrative is credited only when a briefing is shown;
//   · WHO READ THE DOCUMENT is the served extraction method, never a
//     universal sentence (2026-10-02). "Every figure is computed by the
//     deterministic engine from the uploaded trial balance" was printed on
//     every report — including a period whose `extraction.method` is "llm",
//     where a model read the numbers and the same page carries the AI-read
//     badge, and over a valuation section that is arithmetic done in the
//     browser. `reportAuthorship` reads the method once; the in-app footer
//     and the standalone export's basis note (`basisAuthorshipSentence`)
//     both print from it.
//
// Law: lib/__tests__/reportFooter.test.ts (gate public-claims).

import {
  canonicalStatusCore, factsFrom, presentStatus, toDisplay, type BsStatusPresentation,
} from "./servedFacts";
import { moneyLocaleFor } from "./money";
import type { CanonicalBs, Statements } from "./financialReport";

export interface ReportFooterInput {
  /** `GET /api/period` → `statements` (carries `canonical_bs` on every
   *  period the engine verified). */
  statements: unknown;
  currency: string;
  /** True when a briefing body is SHOWN on this report. */
  briefingShown: boolean;
  /** True when the page carries a valuation section computed in the
   *  browser (the signed-in /report page does; the export does not). */
  browserValuation?: boolean;
  /** UI language — the figure's number format follows it (CLAUDE.md §26). */
  language: string;
}

export interface ReportFooterLines {
  /** Who computed what. */
  generated: string;
  /** The engine's balance verdict for this report. */
  balance: string;
  /** The difference to the cent, or that none was served. */
  differenceLine: string;
  /** Machine status — for the test id, never printed. */
  machineStatus: string;
}

/** "-1,234.56 RON" / "-1.234,56 RON": the figure in the reader's number
 *  format, the ISO code after it. */
function amountWithCode(n: number, currency: string, language: string): string {
  const fmt = new Intl.NumberFormat(moneyLocaleFor(language), {
    minimumFractionDigits: 2, maximumFractionDigits: 2,
  });
  // Intl prints "-0.00" for a negative zero; a zero difference has no sign.
  const value = Object.is(n, -0) || Math.abs(n) < 0.005 ? 0 : n;
  return `${fmt.format(value)}\u00a0${currency}`;
}

type Rec = Record<string, unknown>;
const isRec = (v: unknown): v is Rec => typeof v === "object" && v !== null && !Array.isArray(v);

/** The verdict and the difference, read ONLY from the served canonical
 *  balance sheet. A period that carries none has no engine verdict — the
 *  footer says that; it never falls back to totals the page added up. */
function servedBalance(
  statements: unknown, currency: string,
): { p: BsStatusPresentation; diff: number | null } {
  const cbs = isRec(statements) && isRec(statements.canonical_bs) ? statements.canonical_bs : null;
  if (!cbs) return { p: presentStatus({ status: null, currency }), diff: null };
  if (isRec(cbs.totals)) {
    const facts = factsFrom({ canonical_bs: cbs } as unknown as Statements);
    return { p: facts.presentStatus(currency), diff: facts.difference() };
  }
  // A served object without its totals block: the verdict and the drift
  // still come through the gateway's own picks (lib/servedFacts) — this
  // module never reads a canonical_bs field itself.
  const core = canonicalStatusCore(cbs as unknown as CanonicalBs);
  const diff = core.differenceCents === null ? null : toDisplay(core.differenceCents);
  return {
    p: presentStatus({
      status: core.status, needsReview: core.needsReview, difference: diff, currency,
    }),
    diff,
  };
}

/** How the uploaded document's numbers were read, as the engine stamped it
 *  on the served balance sheet (`canonical_bs.extraction.method`, or
 *  `classification.method` for the AI lane — the same two fields the
 *  statement's AI-read badge tests). */
export type ReadBy =
  /** every number read by the deterministic parser */
  | "code"
  /** the numbers were read by an AI model */
  | "ai_model"
  /** an AI model interpreted the layout; the numbers were read by code */
  | "ai_layout"
  /** the served document does not say */
  | "not_stated";

export interface ReportAuthorship {
  readBy: ReadBy;
  /** "trial balance" only when the engine read one of its trial-balance
   *  layouts; any other upload is "document". */
  documentWord: "trial balance" | "document";
}

/** `extraction.source_format` values that ARE a trial-balance layout. A
 *  statutory F30/F10 workbook, a map-guided or a model read is a
 *  "document". */
const TRIAL_BALANCE_FORMAT = /^(saga_\w+|generic_\w+|pdf_positional)$/;

export function reportAuthorship(statements: unknown): ReportAuthorship {
  const cbs = isRec(statements) && isRec(statements.canonical_bs) ? statements.canonical_bs : null;
  const extraction = cbs && isRec(cbs.extraction) ? cbs.extraction : null;
  const classification = cbs && isRec(cbs.classification) ? cbs.classification : null;
  const method = typeof extraction?.method === "string" ? extraction.method : null;
  const format = typeof extraction?.source_format === "string" ? extraction.source_format : "";
  const readBy: ReadBy =
    method === "llm" || classification?.method === "llm"
      ? "ai_model"
      : method === "mechanical_mapped"
        ? "ai_layout"
        : method === "deterministic"
          ? "code"
          : "not_stated";
  return {
    readBy,
    documentWord: readBy === "code" && TRIAL_BALANCE_FORMAT.test(format) ? "trial balance" : "document",
  };
}

/** Who read the document and who computed the figures — one sentence per
 *  reading, none of them universal. */
function readSentence(a: ReportAuthorship): string {
  switch (a.readBy) {
    case "code":
      return `The statements, ratios and credit score in this report were read and computed by ` +
        `code — the deterministic engine — from the uploaded ${a.documentWord}; no AI model read ` +
        `or produced these figures.`;
    case "ai_model":
      return "The figures in this report were read from the uploaded document by an AI model, " +
        "then computed by the engine. Check them against the source before external use.";
    case "ai_layout":
      return "The layout of the uploaded document was interpreted by an AI model; the numbers " +
        "were then read and computed by code.";
    default:
      return "The served statement does not record how the uploaded document was read.";
  }
}

/** The standalone export's basis note: what the figures were computed from
 *  and by whom. `aiNarrative` is true when at least one finding in the
 *  document carries wording an AI model wrote. The export renders no
 *  briefing and no valuation section. */
export function basisAuthorshipSentence(
  statements: unknown, opts: { aiNarrative: boolean },
): string {
  const a = reportAuthorship(statements);
  return (
    readSentence(a) +
    (opts.aiNarrative
      ? " The explanations marked as AI-written under \u201cWhat the numbers say\u201d were worded by an AI model from these figures."
      : "") +
    " Final analytical judgement and any onward decisions remain with management."
  );
}

export function reportFooterLines(input: ReportFooterInput): ReportFooterLines {
  const { p, diff } = servedBalance(input.statements, input.currency);

  const generated =
    "Generated by CFO AI. " +
    readSentence(reportAuthorship(input.statements)) +
    (input.browserValuation
      ? " The valuation section is arithmetic done in your browser on those figures and the " +
        "assumptions shown there."
      : "") +
    (input.briefingShown
      ? " The briefing in section 1 was written by an AI model from these figures."
      : "");

  const differenceLine =
    p.machineStatus === "UNVERIFIED"
      ? "No engine balance verdict exists for this period."
      : diff === null
        ? "Difference: not stated — the served statement carried neither a balance " +
          "difference nor the totals to work one out."
        : `Assets − (Equity + Liabilities) = ${amountWithCode(diff, input.currency, input.language)} on this report.`;

  return {
    generated,
    balance: p.exportHeadline,
    differenceLine,
    machineStatus: p.machineStatus,
  };
}
